### ISSUE TITLE
Change number format ([current_height]/[total_height])

### ISSUE THREAD

**Issue by chatelao** [OllisGit/OctoPrint-DisplayLayerProgress#103]
Is it possible, to send one instead of two digits after the decimal to the printer display?

Reason: my little "RepRap SmartDiscount" display is VERY tight (https://reprap.org/wiki/RepRapDiscount_Smart_Controller)

**Comment by OllisGit** [comment]
Hi @chatelao !
It is implemented in the newest version 1.16.0.

Please test and give feedback!

**Comment by chatelao** [comment]
Great, I have a print pause and will update the plugin immediatly.

**Comment by chatelao** [comment]
ATTENTION: The new option (great) somehow destroyed the plugin-config-menu formatting (setting => ...)

**Comment by OllisGit** [comment]
Hi @chatelao,
the mentioned feature is now included in new version 1.17.0. You can now adjust the number format.
Also the settings-dialog should now be fixed.

Please test and give feedback.

Thx, in advance
Olli
