### ISSUE TITLE
[Enhancement] Add local timezone to "estimated_end_time"

### ISSUE THREAD

**Issue by OllisGit** [OllisGit/OctoPrint-DisplayLayerProgress#108]
As the title says :-)
Add maybe a test/preview-function in Plugin-Settings.

**Comment by brandonscholet** [comment]
This isn't working for me in the current release and I'm not seeing a setting to adjust.

**Comment by OllisGit** [comment]
Hi @brandonscholet ,
please give me more details about "not working"!
I changed the implementation, so that the timezone is picked from the os-system. User settings is not needed. 
Check the clock/timezone on your octoprint-server-host (e.g. raspi).

Because this is a closed enhancement-issue, please raise a new bug-issue or continue in this issue https://github.com/OllisGit/OctoPrint-DisplayLayerProgress/issues/105

**Comment by brandonscholet** [comment]
You were exactly right. Sorry to have bothered you. Keep up the amazing work!

**Comment by Wob76** [comment]
I have update to 1.17.1 and haven't seen any change, 

I tried both Chrome and Edge, 
I also rebooted my Pi and also cleared the browser cache, am I missing something simple?

The Picture is in the Dashboard, the Msg: lines ETA is from DisplayLayer (13:02), the correct ETA is shown in near middle clock icon "00:01:57", Just past midnight.
![Annotation 2020-02-03 210051](https://user-images.githubusercontent.com/199897/73643825-4b5cd500-46c8-11ea-8100-d8cdcb108ffe.png)

**Comment by brandonscholet** [comment]
You have the same problem I have. Your time zone is not correct on the pi. You need to say and copy your timezone over /etc/localtime. This immediately fixed mine.

https://linuxacademy.com/blog/linux/changing-the-time-zone-in-linux-command-line/
https://m.wikihow.com/Change-the-Timezone-in-Linux

**Comment by Wob76** [comment]
You're correct, my /etc/localtime was pointing to Europe/London, must be the default, I have updated the symlink to my actual TZ but it is still showing, might just need a new print job to start or maybe a reboot of the pi, I'll update when I reboot and start my next print.

**Comment by brandonscholet** [comment]
A new print might work, but I just rebooted octoprint. GMT is Zulu time. All timezones are compared to that.

**Comment by Wob76** [comment]
I just tried both tzselect and running raspi-config and still no change, so I think I just need to wait for a new printer\power cycle :)

**Comment by brandonscholet** [comment]
Nice
