### ISSUE TITLE
Underscore added to output.

### ISSUE THREAD

**Issue by jprochazka** [OllisGit/OctoPrint-DisplayLayerProgress#11]
Please refer to the attached image for clarity.
I am running Marlin 1.1.8 and the gcode file was created using Cura 3.2.1.

[img_20180412_023733635](https://user-images.githubusercontent.com/2583357/38660852-c681eb7a-3dfc-11e8-9f32-e64d2c76bd8b.jpg)

If you need more information let me know.

**Comment by OllisGit** [comment]
This a "feature" and not a "bug" ;-)
Because my ANET E10 drops the last character I added the underscore.

I need to implement a kind of "Printer-Dectection" to support my E10 and the "others"

I am thinking about a solution....

**Comment by OllisGit** [comment]
The new Release 1.1.1 is out. Please test the bugfix.
Thx, in advance
Olli
