### ISSUE TITLE
Layers not longer displayed - Anet E10 - Cura sliced

### ISSUE THREAD

**Issue by mc-chick** [OllisGit/OctoPrint-DisplayLayerProgress#118]
Im only get -/- shown for the Layers . Octoprint itself shows the Layers in the GCode Viewer correctly. (on the information section of the gcode viewser i can see the current layer and the target number of layers)

**Comment by OllisGit** [comment]
Hi @mc-chick ,

what versions do you use:
- python
- octoprint

please attach your gcode as well
