### ISSUE TITLE
More descriptive output.

### ISSUE THREAD

**Issue by jprochazka** [OllisGit/OctoPrint-DisplayLayerProgress#12]
Just a thought but not necessary by no means.

Got a lot of room there maybe a more descriptive status line such as:
`25% Printing layer X of X...`
Or something like that so those not in the know know whats going on at a glance.

Push comes to shove if length is an issue in my experience the M73 Progress plugin handles the overall percentage completed so it is displayed in the proper place on a 12864 LCD display or 2004 LCD display so it may not be necessary.

**Comment by OllisGit** [comment]
Thx, for your feedback!
Yes, the statusline is really "naked". I need to optimize this in the near future.

At the moment I didn't use the "M73 Progress-Plugin", but maybe I can adapt this feature as well.

**Comment by OllisGit** [comment]
Also a hint from @TomW1605  in #5 : 

> i would also sagest that having it display the total lines (ether as 0/total or -/total) when you load the file would be better than when the print starts because that would then be in keeping with the behaviour of all the other stats displays already in octoprint.

**Comment by OllisGit** [comment]
The new Release 1.2.0 is out. Please test the enhancement.
@jprochazka  for the "M73 Progress-Plugin" I will create a new issue

Thx, in advance
Olli

**Comment by OllisGit** [comment]
@jprochazka see #20 please test it!
