### ISSUE TITLE
Exclude folder(s)

### ISSUE THREAD

**Issue by ToXIc-Dev** [OllisGit/OctoPrint-DisplayLayerProgress#123]
I am using my printer as a makeshift CNC and when using the gcode files for it this plugin constantly gives me this error notification "Layer indicator not found in file! Check layer pattern in DisplayLayerProgress-Settings and reupload the file!"

I have my files in a separate upload folder called CNC so I was wondering if you could add functionality to exclude a certain folder(s) from analysis (or maybe files with a certain prefix, folder would be better IMO though)

**Comment by OllisGit** [comment]
Hi @ToXIc-Dev ,

nice idea! 
Will check the effort and come back to you.

**Comment by OllisGit** [comment]
Hi @ToXIc-Dev ,
it is implemented in the newest version 1.23.0

Please test and give a feedback

Thx, in advance
Olli
