### ISSUE TITLE
Edit state

### ISSUE THREAD

**Issue by radimkohout** [OllisGit/OctoPrint-DisplayLayerProgress#132]
Hi,
is there any way to edit the state tab on the left? There are current height and layer added by this plugin, but I can't find if I can edit it somewhere

**Comment by OllisGit** [comment]
Hi @radimkohout,
currently there is no edit-option, because I don't see the demand on that.

Please explain in detail why you need such functionality.

**Comment by radimkohout** [comment]
I need it for displaying [estimated_end_time] and [feedrate] in here.

**Comment by OllisGit** [comment]
Hi @radimkohout,
it is implemented in the newest release V1.19.0!

Now you can customise the state-section like the nav-bar.

Please test and give feedback.

Thx, in advance
Olli

**Comment by radimkohout** [comment]
It looks, that everything is working flawlessly. 
Thank you
