### ISSUE TITLE
Spelling error

### ISSUE THREAD

**Issue by mselkin** [OllisGit/OctoPrint-DisplayLayerProgress#134]
There is a spelling error:

In the height menu:

Choose total height methode:

Should be:

Choose total height method:

**Comment by OllisGit** [comment]
Hi @mselkin ,
thanks a lot I appreciate that.
Will be fixed in the next version!

**Comment by mselkin** [comment]
Thank you!

**Comment by OllisGit** [comment]
Hi @mselkin,
it is fixed in the newest release V1.19.0!
