### ISSUE TITLE
Use profiler to improve the performance

### ISSUE THREAD

**Issue by OllisGit** [OllisGit/OctoPrint-DisplayLayerProgress#135]
See https://github.com/OllisGit/OctoPrint-DisplayLayerProgress/issues/127#issuecomment-605349126

See also: https://stackoverflow.com/questions/2522005/cost-of-exception-handlers-in-python

**Comment by gdombiak** [comment]
@OllisGit I think that we can close this ticket now. https://github.com/OllisGit/OctoPrint-DisplayLayerProgress/pull/175 includes fixes for what was discovered by profiling the plugin and also OctoPrint.

Thanks,
Gaston
