### ISSUE TITLE
Layer analysis does not work in all cases.

### ISSUE THREAD

**Issue by MarshMalloW0007** [OllisGit/OctoPrint-DisplayLayerProgress#138]
When the file is uploaded via drag and drop, everything is fine, the file is modified with M117s.

With Simplify3D
  layer 1, Z = 0.180
becomes
  layer 1, Z = 0.180
  M117 INDICATOR-Layer1

When the same file is placed on the server with scp or the GitFiles plugin, when you want to print it, the layer analysis doesn't work and there is an error popup :
   Layer indicator not found in file: '***.gcode'.
   Check layer pattern in DisplayLayerProgress-Settings and reupload the file!

Tested on two OctoPi installations with the Dashboard and DisplayLayerProgress plugins:
  OctoPrint version : 1.4.0
  OctoPi version : 0.17.0
  Dashboard : 1.11.4
  DisplayLayerProgress : 1.19.1

English is not my native language...
Kind regards,
Marsh

**Comment by OllisGit** [comment]
Hi @MarshMalloW0007 ,

adding the M117 INDICATORS is only done via Upload-API (Browser Drag&Drop or API-Call from Slicer).

If you copy files via SCP or on an other way, the Layer-Indicator will not added. You need to configure your slicer to do that for each layer.

BR
Olli
