### ISSUE TITLE
OctoPod & Print Time

### ISSUE THREAD

**Issue by Neiljclements** [OllisGit/OctoPrint-DisplayLayerProgress#139]
Just a quick question about the OctoPod compatibility. The latest version broke it and people had to rewind to the previous version, so I was wondering when the latest version of DisplayLayerProgress will be released please? It will have the OctoPod compatibility built in, yes? I know Gaston is keen to open a line of dialogue with you for future releases and how you can be of help to each other.

Secondly, there was a possibility of calculating layer time from the layer progress average with your add on. Did anything ever come of this? It has got to be way more accurate than OctoPrint calculation, which gives ridiculously stupid print times.

Thanks for a great app. Super useful 😊👍🏽

**Comment by OllisGit** [comment]
Hi @Neiljclements ,

regarding OctoPod, new DLP Version 1.20.0 is out, see also https://github.com/OllisGit/OctoPrint-DisplayLayerProgress/issues/136

I am not sure what you mean with "there was a possibility of..". 
The current implementation doesn't support this and it also not planed to support this.
I think it is also not really exact. Just print a cone. Each top layer will be faster then the layers below.
Maybe this is already implemented in the Dashboard-Plugin from StefanCohen...I don't know.

Didi you already try this: https://plugins.octoprint.org/plugins/PrintTimeGenius/

**Comment by StefanCohen** [comment]
So far the Dashboard just tracks the layer progress per layer as reported by OctoPrint.

**Comment by OllisGit** [comment]
PTG integration in DLP is planed, see  https://github.com/OllisGit/OctoPrint-DisplayLayerProgress/issues/144
