### ISSUE TITLE
add settings page

### ISSUE THREAD

**Issue by TomW1605** [OllisGit/OctoPrint-DisplayLayerProgress#14]
i think a settings page that lets you chose what to display (progress/layers/both) on the printer and navbar separately would be good. also when available put an option here to move it from navbar to sidebar.

**Comment by TomW1605** [comment]
it could even allow custom formatting with placeholders for progress (`[progress]`), curent layer (`[layer]`) and max layer (`[max_layer]`)

**Comment by OllisGit** [comment]
Yes, I am implementing this right now:
Location-Option and what to output.

**Comment by TomW1605** [comment]
i just noticed that your solution to the underscore issue was to check if it your printer and only add it if it is. this is good for now but this would be something else worth adding to the settings.

**Comment by TomW1605** [comment]
on further reflection i think `[PROGRESS]`, `[CURRENT_LAYER]` and `[MAX_LAYER]` would be better placeholders

**Comment by OllisGit** [comment]
Good point! 
I will add this to the "setting-page" enhancement.

**Comment by OllisGit** [comment]
The new Release 1.2.0 is out. Please test the enhancement.
Thx, in advance
Olli
