### ISSUE TITLE
Display completion percentage and completion time from PrintTimeGenius

### ISSUE THREAD

**Issue by mdaneman** [OllisGit/OctoPrint-DisplayLayerProgress#144]
I have both DLP and PrintTimeGenius installed. However, I noticed that that percent complete and estimated completion time that DLP displays are from raw Octoprint which can be grossly in accurate. Would it be possible to have an option for DLP to display the estimates from PTG instead?

**Comment by OllisGit** [comment]
Hi @mdaneman ,
I didn't look into the PTG-Plugin, so at the moment I have no idea if PTG provide the values for other plugin developers. Maybe there is an Interface.

I also thought about this....maybe I will implement this in the future.

**Comment by OllisGit** [comment]
I think this is solved with the latest version 1.23.3.
