### ISSUE TITLE
Can the estimated time finished be AM/PM

### ISSUE THREAD

**Issue by jbuszkie** [OllisGit/OctoPrint-DisplayLayerProgress#150]
Right now it is display the estimated finish time in 24H time.  Can that be changed to AM/PM?  I hate having to subtract 12 all the time! :-)

**Comment by OllisGit** [comment]
Hi @jbuszkie ,

in the newest version 1.22.0 you can adjust the timeformat in the plugin settings.

Please test and give feedback.
Thx,
Olli

**Comment by jbuszkie** [comment]
Looks like it works..  Thanks!
