### ISSUE TITLE
Fixed total height at 123 layers / 20mm

### ISSUE THREAD

**Issue by markus1802** [OllisGit/OctoPrint-DisplayLayerProgress#153]
Hi,
first the total height wasn't displayed at all. I then reset the setttings in the octoprint plugin settings dialog. Since then the total layer height is always displayed as 123 and the total height as 20mm. This is even if the model is way larger (or smaller). See attached screenshot. I'm using CURA 4.6.1. My Ender 3 runs Marlin 1.1.9.
Any idea what may be wrong here?
Thanx
Markus
![2020_05_30_13_41_54_63_14_06](https://user-images.githubusercontent.com/65816190/83327805-f51b2f80-a27e-11ea-8e00-527fa2baa463.png)

**Comment by markus1802** [comment]
This is a snippet of the gcode from the above screenshot. I downloaded it from octoprint after printing.
...
M83 ;relative extrusion mode
G1 F1500 E-2
;LAYER_COUNT:293
;LAYER:0
M117 INDICATOR-Layer0
M106 S51
...

**Comment by markus1802** [comment]
New variant: the total layers are always displayed as 45. Total height still is 20.0 on every print. 

The print in the screenshot has 490 total layers.

![screenshot](https://user-images.githubusercontent.com/65816190/83790672-d7900080-a698-11ea-84f5-0142f7e73489.png)

**Comment by OllisGit** [comment]
Very strange!
Can you please attach the original and the modified gcode downloaded from OP to this issue?

Then I can debug the processing during print.

**Comment by markus1802** [comment]
Thank you for your answer! 
I understand that the file is changed during print (from OctoPrint?). I use "Print with OctoPrint" from Cura. Therfore I usually don't have the file before printing. Because of that I attached a zip with the file downloaded from OctoPrint (while the print currently is still printing, it's a larger print) and a file I just now saved to file from Cura (the object with unchanged settings was still opened). Hopefully this helps. Otherwise I have to make a new test when this print finished.

**Comment by markus1802** [comment]
I just compared both files by myself. I used german characters in the filenam. Stupid! But I think that's not the problem because I had this behaviour with other files also. The only difference I found is an added:
M117 INDICATOR-Layer0
on every layer.

;LAYER_COUNT:490 also looks good for me.

**Comment by OllisGit** [comment]
hmm..I just uploaded the file ```_from_cura``` and everything looks fine after file selection.
![image](https://user-images.githubusercontent.com/24205767/83809692-319fbe80-a6b7-11ea-9a9e-93a1e5da9ed4.png)
Also the modified file you provided includes 490 layer-indicators.

After uploading to my test-printer, the ```;MESH``` comment is not modified. This is not a "feature" of my plugin. I have no idea if the printer can handle this command: ```@Object D??bel-Hilfe1.stl``` 

What other plugins do you use?

You already executed the reset-settings button, but please take a look directly into the OP ```config.yml``` file.
The location could be found in the Folders-Section. Use the Upload Folder and go one directory above. In that root folder there should be the config.yml file.
If the reset was executed successful, you should not find any entry for DisplayLayerProgress
```
plugins:
    DisplayLayerProgress:
        layerOffset: '1'
```

**Comment by markus1802** [comment]
I did some more testing:

1. Yesterday I got an update to the Cura-OctoPrint-Connection. Because of that I first made a new test print -> 45 total layers

2. config.yaml showed:
    DisplayLayerProgress:
        layerOffset: '1'
        showAllPrinterMessages: false
So I made a new Reset Settings. Test print -> 45 total layers

3. I searched for ;MESH and @Object: must be a "feature" of CancelObject-Plugin. So I uninstalled CancelObject and restarted OctoPrint. Test print -> 489 total layers

4. Installed CancelObject again. Test print -> 489 total layers

Ok, that's really strange. Obviously CancelObject was the cause. Anyways, it's working again. Thank you for your support and sorry for bothering you.

**Comment by markus1802** [comment]
Hi,
unfortunately I have to reopen this issue. As of my comment above the last print data looked correct. But the total layer got stuck at this 489 total layers for all following prints.

I now have totally uninstalled the CancelObject-Plugin. The DisplayLayerProgress-Plugin I have uninstalled (with deleting data) and reinstalled. 

Result ist:
![screenshot](https://user-images.githubusercontent.com/65816190/83975579-d6f3a600-a8f4-11ea-9c2f-9d2390c43ac3.png)

The printed object has a total layer count of 42 and a total height of 8.4mm. From the beginning of the print till it's end OctoPrint shows 20mm and 52 layers. I lastly didn't print anything with total layers of 52. Totally confusing.

I add the gcode files:
[gcode2.zip](https://github.com/OllisGit/OctoPrint-DisplayLayerProgress/files/4742602/gcode2.zip)

Do you have any idea what I may check?

**Comment by markus1802** [comment]
Ok, I uninstalled more Plugins:
- Floating Navbar
- Printoid

Now, the total layers are displayed correct. I started several test prints with larger oder smaller objects and the total layers were always as expected. But the total height still shows 20.0mm if the object is smaller than 20.0mm. If it's larger the expected size is shown.

**Comment by OllisGit** [comment]
Hi @markus1802 ,
I will install the mentioned. plugin and try to reproduce the issue.

**Comment by JayceeB1** [comment]
Hi

also got some strange issues using Cura 4.6.1

![image](https://user-images.githubusercontent.com/45721154/85197952-e1df0b00-b2e4-11ea-94da-0b8520611c64.png)

**Comment by OllisGit** [comment]
Hi @JayceeB1 ,

please provide the gcode downloaded from OP, maybe it is a different issue.
Do you also use the Plugin "Cancel Object"?

@markus1802 I installed "Cancel Object" and now I can reproduce the error. The max layer count is not changed anymore.
I will start analysing the issue a little bit deeper the next days.

**Comment by OllisGit** [comment]
fyi: I only could reproduced the behaviour once. Now everything is working. Hard to find the issue.
