### ISSUE TITLE
No layer / total layer display on browser and printer screen

### ISSUE THREAD

**Issue by mikebzh44** [OllisGit/OctoPrint-DisplayLayerProgress#16]
Hi.

I'm using v1.1.1 and I don't have statitics displayed on octoprint web page (I only have Layer: - / -) or on printer screen (only the percentage).

I'm printing this file, sliced par S3D : 

https://www.dropbox.com/s/jpiso26hruh4mps/Lack_Angle_x3.gcode?dl=0

The same file was OK with previous release of your plugin.

**Comment by mikebzh44** [comment]
It's after editing GCode file and removing "; layer end" line ;)

**Comment by OllisGit** [comment]
The new Release 1.2.0 is out. Please test the bugfix.
Thx, in advance
Olli
