### ISSUE TITLE
Day of week in [estimated_end_time]

### ISSUE THREAD

**Issue by mikulik86** [OllisGit/OctoPrint-DisplayLayerProgress#162]
I propose that if [estimated_end_time] is more than 24 hours, it should be displayed with day of week. For example: "Friday 18:36".
Better yet, "Tomorrow 18:36" if the ETA is the next day.

**Comment by OllisGit** [comment]
Hi @mikulik86 ,

because everybody wants a different output, I implemented the option to format the output by your self.
In your case you just need to change the time format to ```%A %H:%M'.
You cant test it here: https://trinket.io/python/b2055e0d6d
![image](https://user-images.githubusercontent.com/24205767/89667344-4594b600-d8dc-11ea-86fa-bce38a0bf97e.png)
The explanation of the format could be found here: https://www.programiz.com/python-programming/datetime/strftime#format-code

Btw. "Tomorrow" is not possible.

**Comment by mikulik86** [comment]
Thank you! 
Could you just point me on how to use it? Because i have no idea :D

**Comment by OllisGit** [comment]
Hi @mikulik86 ,
just go to the Plugin-Settings
![image](https://user-images.githubusercontent.com/24205767/90291828-fec93200-de80-11ea-8dd0-7cdc4c78e289.png)
Result:
![image](https://user-images.githubusercontent.com/24205767/90291753-dc371900-de80-11ea-98d1-5b97157029f6.png)

**Comment by mikulik86** [comment]
Totally overlooked it, sorry. Should have go through the settings more thoroughly. Nice implementation though 👍
Thanks!
