### ISSUE TITLE
wrong percentage??

### ISSUE THREAD

**Issue by spanzetta** [OllisGit/OctoPrint-DisplayLayerProgress#163]
Which one is wrong?
;-)

Is it 96% or 99%?

![Clipboard01](https://user-images.githubusercontent.com/49818743/89738798-d2c24100-da7b-11ea-8e8b-89ac19a586c1.jpg)

It is wrong 96% !!
![Clipboard02](https://user-images.githubusercontent.com/49818743/89738843-15841900-da7c-11ea-9aec-e3dc43326bc0.jpg)

**Comment by spanzetta** [comment]
even worst here..

what's happening???

![Clipboard01](https://user-images.githubusercontent.com/49818743/89773243-d4cfe280-db03-11ea-8063-7d531350b073.jpg)

**Comment by allenrowand** [comment]
Same issue here. I used Themeify to hide the progress bar, then added the DLP progress percentage next to the layer count in the State sidebar so that it matches the printer's display. Not perfect, but at least I see a consistent percentage now.

**Comment by OllisGit** [comment]
Hi @spanzetta , @allenrowand ,
which OctoPrint Version and Python Version do you use?

Please also provide the octoprint.log, maybe there is an error occurred.

**Comment by allenrowand** [comment]
I'm on OctoPrint 1.4.2, Python 2.7.16, OctoPi 0.17.0.

I've attached my logs from yesterday, there were several prints and attempted prints. Thanks!

[octoprint.log](https://github.com/OllisGit/OctoPrint-DisplayLayerProgress/files/5077279/octoprint.log)

**Comment by The-EG** [comment]
I'm seeing the exact same issue on a brand new install of OctoPrint, basically the same setup as allenrowand (I came here to post an issue and found this!)

**Comment by OllisGit** [comment]
Hi @spanzetta
which version of OP and Python do you use? Maybe the issue is related to newest OP-Release.

In my dev-environment I can't reproduce the error.

**Comment by OllisGit** [comment]
Hi, 
I looked into the sourcecode and currently I don't have an explanation how this could happen.

In the newest version 1.23.0 I added more log - informations in the plugins event-log.
Please activate the event-logging in the plugin settings and if the error occurs, please download the ```plugin_DisplayLayerProgress_events.log``` file and attach it to this issue.
![image](https://user-images.githubusercontent.com/24205767/90447683-1bb16f80-e0e4-11ea-8088-91d4fc5ada06.png)

Thx, in advance
Olli

**Comment by allenrowand** [comment]
[plugin_DisplayLayerProgress_events.log](https://github.com/OllisGit/OctoPrint-DisplayLayerProgress/files/5087382/plugin_DisplayLayerProgress_events.log)
<img width="287" alt="Screen Shot 2020-08-17 at 4 34 58 PM" src="https://user-images.githubusercontent.com/32688520/90455829-f3a61a00-e0ab-11ea-8985-9e7f0f8beaef.png">

Thank you for following up on this, let me know if there's anything else I can do to help.

**Comment by OllisGit** [comment]
hmm... thanks for the log. I took a rough look into the file and I think I found the issue... but at the moment I have no idea how to solve it.

In the last versions/month I captured a lot of new events with a lot of "cool" values which could be send to the display.
Because of increasing the amount of events the performance of the OP-Server decreased (could be the reason for layer-shifts).
So, I changed the processing behaviour to a queuing async-way. Now the performance is good, but each display event is processed after each other and creates a delay between occurring and displaying.

In your case:
```
-- Received the 1% progress changed event
16:29:38,939 ON_PRINT_PROGRESS: 1 [1704100960::Thread-61]
...a lot of other events
-- Send the progress change to the display
16:34:44,510 SEND-COMMAND: M117 1% L=-/100 40.0mm [1704100960::Thread-63]

--> delay of 5 seconds
```

Can you confirm a delay of ~5 seconds?
Please also provide the octoprint.log.

Btw. turn off the event log, because it could create huge log files.

**Comment by allenrowand** [comment]
It's only a second or two between I see the progress change in the state sidebar and when it updates on the printer's display. The issue for me is the plugin shows a completely different progress value than the progress bar; in the screenshot above the plugin is reporting 1% completion while the progress bar shows 17%.

**Comment by allenrowand** [comment]
Here's my octoprint log; there's now a ton of error messages regarding notifications. I don't recall seeing this before I upgraded DLP to version 1.23.0
[octoprint.log](https://github.com/OllisGit/OctoPrint-DisplayLayerProgress/files/5092294/octoprint.log)

**Comment by OllisGit** [comment]
Hi @allenrowand ,

you use a lot of other plugins, did you try to deactivate other plugin to see an improvement/change. E.g. disabling ActionCommands, produce a lot of noise....and btw. I looked into the implementation and the author did the same mistake I did in the past. The plugin use a OP-Hook in the communication layer.
https://docs.octoprint.org/en/master/plugins/hooks.html#octoprint-comm-protocol-action

>Warning
>
>Make sure to not perform any computationally expensive or otherwise long running actions within your handlers as you will effectively block the receive loop, causing the communication with the printer to stall.
>
>This includes I/O of any kind. 

But maybe this is not related to the current issue.

**Comment by allenrowand** [comment]
I removed a few plugins, but if I unhide the progress bar it still shows a different completion percentage from what DisplayLayerProgress shows on the printer display, browser tab, and state area of OctoPrint:
<img width="288" alt="Screen Shot 2020-08-20 at 1 42 20 PM" src="https://user-images.githubusercontent.com/32688520/90825289-8f729880-e2ed-11ea-95f1-43772b5bdd00.png">

My expectation is that the 90% shown by DLP would be the same as the 96% in the progress bar. Is your code generating the blue progress bar, or is that value coming from someplace else?

I'll file a bug re: ActionCommands spurious logging.

**Comment by bvrielink** [comment]
Got the same problem. At the moment a 21% difference (73% instead of 94%). Got a lot of plugins but most are for visual stuff etc. Only plugin which could be a problem is maybe PrintTimeGenius. Unfortunately I am not willing to disable plugins but I can help with debug or logging of needed.

**Comment by OllisGit** [comment]
Hi @bvrielink ,

next time you print please do the following:

- turn on event-logging in DLP-Settings
- check size of octoprint.log sometimes it is big and should be delete before a debug-print starts
- restart server
- start print
- after print. please attache two log-files to this issue (octoprint.log and plugin_DisplayLayerProgress_events.log)
- turn off DLP event-logging

Thx,
Olli

**Comment by bvrielink** [comment]
> 
> 
> Hi @bvrielink ,
> 
> next time you print please do the following:
> 
>     * turn on event-logging in DLP-Settings
> 
>     * check size of octoprint.log sometimes it is big and should be delete before a debug-print starts
> 
>     * restart server
> 
>     * start print
> 
>     * after print. please attache two log-files to this issue (octoprint.log and plugin_DisplayLayerProgress_events.log)
> 
>     * turn off DLP event-logging
> 
> 
> Thx,
> Olli

Hi @OllisGit , 

See attachment for logging. I did a slight search/replace in the OctoPrint log file btw (ip's and usernames)

It's from a cancelled print which ran for a couple of hours. At some point the difference was huge. It showed for example 12% but it was already at 62%. All other plugins like M73 Progress (which I only installed today) transfer the correct percentage to the printer. Makes me curious where the percentage for this plugin comes from. 

Hope you can find the problem. Let me know if you need more info.

[layer.zip](https://github.com/OllisGit/OctoPrint-DisplayLayerProgress/files/5175429/layer.zip)

**Comment by spanzetta** [comment]
problem still present,,, I hope it can be fixed by the author..

**Comment by spanzetta** [comment]
Is there any news on this topic?
Thanks a lot

**Comment by bvrielink** [comment]
When I look at the code this plugin does not factor in plugins which change/improve the progress (as PrintTimeGenius does for example). If I look at plugin Progress Title (https://github.com/pwnbus/OctoPrint-Progress-Title) which does show the percentage correctly it does take this into account:

                   if (self.custom_time_plugin){
                        // References the PrintTimeGenius plugin
                        percentage_completed = (data.printTime||0) / ((data.printTime||0) + (data.printTimeLeft)) * 100;
                    }

Hope @OllisGit can change this. If not I will make a fork as I quite like PrintTimeGenius.

**Comment by spanzetta** [comment]
> Hi @spanzetta
> which version of OP and Python do you use? Maybe the issue is related to newest OP-Release.
> 
> In my dev-environment I can't reproduce the error.

Hi @OllisGit 
Here is my details..

Raspberry PI 3A+
OctoPrint 1.4.2
Python 2.7.16
OctoPi 0.17.0

Waiting for your feedback... and I hope you can fix the problem.. it happens always/consistently..

**Comment by OllisGit** [comment]
Question: Who is using "PrintTimeGenius"? If you disable this plugin, is the lack gone?

**Comment by OllisGit** [comment]
Hi @bvrielink,
I looked into the ProgressTitel and PTG implementation and both overwrite the viewmodel behaviour of the progressbar  to include the PTG values instead of the system progress value.

Now the question is, how could this UI values send to the DLP-Plugin, so that the plugin could spread this info to: the printer-display and the other UI fragments that DLP supports (also the EventBus and the public API)?

Do you have any ideas how your PR could look like? Ideas welcome!!

**Comment by allenrowand** [comment]
> Question: Who is using "PrintTimeGenius"? If you disable this plugin, is the lack gone?

I use PTG, will test as soon as I can.

**Comment by bvrielink** [comment]
> PrintTimeGenius

I am using PrintTimeGenius as well. Before I used PrintTimeGenius there was no lag. But the print estimates were not correct because the estimates from OcoPrint are very inaccurate that's why I use PrintTimeGenius which solves this problem.

**Comment by bvrielink** [comment]
> 
> 
> Hi @bvrielink,
> I looked into the ProgressTitel and PTG implementation and both overwrite the viewmodel behaviour of the progressbar to include the PTG values instead of the system progress value.
> 
> Now the question is, how could this UI values send to the DLP-Plugin, so that the plugin could spread this info to: the printer-display and the other UI fragments that DLP supports (also the EventBus and the public API)?
> 
> Do you have any ideas how your PR could look like? Ideas welcome!!
> 
> Currently I am using this "backend" function, but this could only deliver the system-progress and not the PTG progress:
> 
> ```
> def on_print_progress(self, storage, path, progress):
> ...
> ```

Hi @OllisGit ,
My suggestion would be to look if a linear time plugin is installed and if so don't use the system progress but calculate it like in the example above. Took a look a couple of days ago and I believe only printTimeLeft was missing atm in your plugin. If that is available it's not a lot of work for the display part but to be honest I didn't look at the API and EventBus stuff so maybe that's another story.

**Comment by OllisGit** [comment]
fyi: I found a way to solve the issue, but I need to do more testing.

**Comment by bvrielink** [comment]
> 
> 
> fyi: I found a way to solve the issue, but I need to do more testing.

Great! If you want me to test as well let me know.

**Comment by spanzetta** [comment]
@OllisGit 
That's a great news!
Let's wait the results of your testing..
Thanks

**Comment by OllisGit** [comment]
Hi,

new version 1.23.3 is out.

If PrintTimeGenius is used, the progress is calculated instead of using the system progress value.
Now there is no huge gap between progress bar and display. Sometimes the progress is is slightly ahead, maybe a rounding issue or a higher update interval. But I think this is acceptable.

Please test and give feedback.

BR
Olli

**Comment by bvrielink** [comment]
Hi @OllisGit ,

Did a quick test and during the print it seems to be okay now. Sometimes a percentage above like you said but that's no problem. What is a pity that it only updates the percentage during the actual print. My print progress was already at 10% because of heating and abl but the progress stayed at 0% until it actually started printing (then it jumped from 0% to 10% immediately). Don't know if you want/can fix that but that's at least my observation.

**Comment by spanzetta** [comment]
I confirm that now it works almost perfectly..
Good job!!!
Thanks

**Comment by allenrowand** [comment]
Confirmed to be much better here, thank you! Now I'm removing the text display from the progress bar; I have Themeify set .progress-text-front to display:none
<img width="289" alt="Screen Shot 2020-09-20 at 10 06 28 AM" src="https://user-images.githubusercontent.com/32688520/93717222-2e76f400-fb29-11ea-9747-204c3d2ad5be.png">

**Comment by spanzetta** [comment]
Sorry to come back here.. but I have a question even if not directly related to this plugin..
Now all percentage shown is correct.. but they are not in the notifications sent by both PushBullet and Telegram plugins (eg. it is printing at 30% but the notifications says 7% )
Do you have an idea on where the wrong data is read by PushBullet/Telegram plugins?
Should we report this issue to their author?

Thanks

**Comment by OllisGit** [comment]
Hi @spanzetta ,

the problem is, that the PTG-Plugin overwrite the time-calculation stuff in OctoPrint, but not the progress-calculation. Thats the reason that each plugin needs to adjust the progress by it's own, like I did or the OctoPrint-Progress-Title did.

So, you need to raise an issue for each plugin that use the progress-value.

**Comment by spanzetta** [comment]
Ok 
thanks for the clear explanation
