### ISSUE TITLE
Display bed temperature in browser title

### ISSUE THREAD

**Issue by mucolon** [OllisGit/OctoPrint-DisplayLayerProgress#164]
This isn't an issue at all, but more of a feature request. Hopefully someone has some extra time and can add this functionality. Thanks in advance and great job with the plugin so far.

**Comment by OllisGit** [comment]
Hi @mucolon, 
should be easy to implement. I will take a look.

**Comment by mucolon** [comment]
That's great news. Thank you!

**Comment by OllisGit** [comment]
Hi @mucolon,
it is implemented in the newest version 1.23.0

Please test and give a feedback

Thx, in advance
Olli

**Comment by mucolon** [comment]
@OllisGit Just finished using it, it's working great. Thank you again.
