### ISSUE TITLE
How does one set their time zone for ETA

### ISSUE THREAD

**Issue by sr1329** [OllisGit/OctoPrint-DisplayLayerProgress#165]
Hi I'm trying to figure out how to set an offset for accurate ETA in my time zone.

**Comment by allenrowand** [comment]
1. SSH into the Pi
2. Run sudo raspi-config
3. Select Localization Options, then Change Timezone
4. Select your geographic area, then the closest city within your timezone
5. When you get back to the main screen select Finish

**Comment by sr1329** [comment]
Thank you

On Aug 19, 2020, at 1:06 PM, allenrowand <notifications@github.com> wrote:

﻿

  1.  SSH into the Pi
  2.  Run sudo raspi-config
  3.  Select Localization Options, then Change Timezone
  4.  Select your geographic area, then the closest city within your timezone
  5.  When you get back to the main screen select Finish
