### ISSUE TITLE
Missing "total layer hight"

### ISSUE THREAD

**Issue by energiebrand** [OllisGit/OctoPrint-DisplayLayerProgress#166]
I am missing the total layer hight since some days. Don´t know when this problem started.
The screenshot shows that there is no more the folder "Height". Did you remove this?

[octoprint.log](https://github.com/OllisGit/OctoPrint-DisplayLayerProgress/files/5108551/octoprint.log)
![LAYER-1](https://user-images.githubusercontent.com/60507600/90885240-8519d280-e3b1-11ea-8888-c47c806405a6.jpg)
![Versions](https://user-images.githubusercontent.com/60507600/90885335-aed2f980-e3b1-11ea-81bc-33239b4879b0.jpg)

![LAYER-1](https://user-images.githubusercontent.com/60507600/90885376-c4482380-e3b1-11ea-8d67-4e93c406c1fb.jpg)
[Temp_tower_PLA.gcode.txt](https://github.com/OllisGit/OctoPrint-DisplayLayerProgress/files/5108566/Temp_tower_PLA.gcode.txt)

![Hight_3](https://user-images.githubusercontent.com/60507600/90886217-48021000-e3b2-11ea-9c74-33a054395d59.jpg)
![Hight_2](https://user-images.githubusercontent.com/60507600/90886219-489aa680-e3b2-11ea-8b48-e9a1bec26736.jpg)

**Comment by energiebrand** [comment]
In addition...today I made 1st time an upload from CURA to my FRITZBOX internal NAS, then a download to a RPi4 in my printer room and then an upload from the RPi4 to the RPi3B  with Octoprint. Max layer hight is shown! So it is always a problem of the direct download from CURA directly to Octoprint.

**Comment by OllisGit** [comment]
fyi: I could reproduce the issue with Cura...will try to find a solution.

**Comment by energiebrand** [comment]
Great that are able to reproduce it!
Please also do not forget the little problem: https://github.com/OllisGit/OctoPrint-DisplayLayerProgress/issues/166#issuecomment-678614851
I´m not sure but I think I remember that problem was also in an earlier release...(?)

**Comment by OllisGit** [comment]
@energiebrand for the dashboard issue, see https://github.com/StefanCohen/OctoPrint-Dashboard/issues/193

**Comment by OllisGit** [comment]
Hi @energiebrand ,

new version 1.23.1 is out, please test and give feedback.

Thx, in advance
Olli

**Comment by energiebrand** [comment]
Thanks a lot! First impression: look great and seems to work on 2 RPi´s! Unfortunately some other users opened issues that "normal" upload seems to work not anymore. So I did some tests and currently everything seems to work on my RPi´s. In detail:

- OctoPrint 1.4.2 Python 2.7.13 OctoPi 0.16.0 
    -> CURA 4.7 -> saved file on PC -> upload to NAS server -> upload to RPi -> works

- OctoPrint 1.4.2 Python 2.7.16 OctoPi 0.17.0
     -> CURA 4.7 -> saved file on PC -> upload to NAS server -> upload to RPi -> works
     -> CURA 4.7 -> saved file on USB Stick -> USB stick to USB port of control RPi with browser -> upload to RPi via drag&drop -> works
    -> CURA 4.7 -> saved file on USB Stick -> USB stick to USB port of control RPi with browser -> upload to RPi via UPLOAD button -> works
    -> CURA 4.7 -> **direct upload to RPi** -> works

So currently solved for me. I can do the additional tests also on the "OctoPrint 1.4.2 Python 2.7.13 OctoPi 0.16.0" installation but currently there is a print job running...

**Comment by energiebrand** [comment]
Added following test:
- OctoPrint 1.4.2 Python 2.7.13 OctoPi 0.16.0:
   -> CURA 4.7 -> **direct upload to RPi** -> works
   -> CURA 4.7 -> saved file on PC -> upload to RPi via UPLOAD button -> works
   -> CURA 4.7 -> saved file on PC -> upload to RPi via drag&drop -> works

**Comment by energiebrand** [comment]
Hmmm, I am still on 1.23.1 since my both RPi installations cannot detect a new release 1.23.2 even if I let them serch for a new release. Maybe I have to delete the old release and install manually...?
However the 1.23.1 is still working perfectly. I´m running 2 new prints on both installations currently with direct upload from CURA 4.7 and max. layer hight is shown. Give me one more day for the update and I will give feed back if there are not new issues with 1.23.2

**Comment by energiebrand** [comment]
OK, had to clear the cache. Now on 1.23.2 on my  "OctoPrint 1.4.2 Python 2.7.16 OctoPi 0.17.0" and tested:
-> CURA 4.7 -> direct upload to RPi -> works
-> CURA 4.7 -> saved file on PC -> upload to RPi via UPLOAD button -> works
-> CURA 4.7 -> saved file on PC -> upload to RPi via drag&drop -> works

**Comment by energiebrand** [comment]
Testing finished successfully on "OctoPrint 1.4.2 Python 2.7.13 OctoPi 0.16.0":
-> CURA 4.7 -> direct upload to RPi -> works
-> CURA 4.7 -> saved file on PC -> upload to RPi via UPLOAD button -> works
-> CURA 4.7 -> saved file on PC -> upload to RPi via drag&drop -> works

From my point of view closing this bug is an option :-) Thanks a lot!
