### ISSUE TITLE
New update breaks insertion of layers function

### ISSUE THREAD

**Issue by Crowlord** [OllisGit/OctoPrint-DisplayLayerProgress#169]
1.23.0 update

On update the layer insertion feature triggers the following error in Prusa Slic3r.

```
Error uploading to print host:
HTTP 500: <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>500 Internal Server Error</title>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.</p>
```

Was fine before update and switching of feature allows upload as before.

**Comment by ifekali** [comment]
Same here. Unfortunately this breaks the Dashboard plugin also, depending on this one.

Until fixed, is there a way to revert to previous version?

**Comment by Crowlord** [comment]
Also occurs if directly uploaded 

![image](https://user-images.githubusercontent.com/26388416/91659894-96a65d00-eaca-11ea-9246-5e0307895785.png)

**Comment by OllisGit** [comment]
SORRY!!!

New version 1.23.2 is out and fix the upload functionality!

**Comment by Crowlord** [comment]
Confirmed fixed
