### ISSUE TITLE
Fan speed does not update when the speed is changed from the Marlin firmware screen

### ISSUE THREAD

**Issue by StarNamer** [OllisGit/OctoPrint-DisplayLayerProgress#171]
**Is your feature request related to a problem? Please describe.**

Marlin firmware has an option REPORT_FAN_SPEED which causes the code to send a string "M106 P<fan> S<Speed>" on all serial ports,e.g "M106 P0 S127" for 50% on fan 0. With this enabled in firmware, it can been seen in the OctoPrint terminal window, but the value of [fanspeed] does not update.

**Describe the solution you'd like**

When the fan speed is changed and the report is sent from the Marlin firmware, the fanspeed should update to reflect the actual speed.

**Describe alternatives you've considered**

No obvious alternative.

**Additional context**

I've confirmed that the M106 messages appear in the terminal window so are being sent by Marlin from appropriately configured firmware. This may require that OctoPrint parse the message received?

**Comment by OllisGit** [comment]
Hi @StarNamer,
I am using this regular expression to detect the fan speed gcode command:
```
^M106.* S(\d+\.?\d*).*"
```
and from your provided sample the value should be ```127```
![image](https://user-images.githubusercontent.com/24205767/93013689-0e848500-f5ab-11ea-9d56-61230e577db7.png)

But as you already mentioned, DPL only parse the uploaded gcode commands from the file itself, it doesn't handle responses from the printer.
