### ISSUE TITLE
Print button clickable while print is running

### ISSUE THREAD

**Issue by zaphod82** [OllisGit/OctoPrint-DisplayLayerProgress#172]
After installing plugin, the print button remains clickable when printer is printing.  Removing the plugin resolves the issue.  Adding the plugin back and issue reappears.

**Comment by zaphod82** [comment]
![Capture](https://user-images.githubusercontent.com/6144821/94330668-70fe5d80-ff7b-11ea-8342-c0cba92de544.JPG)

Screenshot of issue.

**Comment by zaphod82** [comment]
DisplayLayerProgress Plugin (1.23.3)
OctoPrint version : 1.4.2
OctoPi version    : 0.17.0

**Comment by OllisGit** [comment]
Hi @zaphod82,

thx for reporting the issue. 
The fix will be in the next release. Because it is not a critical bug it could take some time when I release a new version with more fixes or features.

**Comment by zaphod82** [comment]
Understandable.  Just wanted to report it as if things aren't reported, no one knows about them and they will never be fixed.

**Comment by OllisGit** [comment]
Hi @zaphod82 ,
it is now fixed in Version 1.24.0.

Please test and give feedback.

Thx, in advance
Olli
