### ISSUE TITLE
Printer Display info pop-up always shows even if "Printer Display" is unchecked

### ISSUE THREAD

**Issue by watermelonpizza** [OllisGit/OctoPrint-DisplayLayerProgress#176]
This seems to be a similar/same error to #66? 
I have installed the plugin version 1.24.0 on octoprint 1.4.2.

If I untick the show setting I just get an empty pop-up.
![image](https://user-images.githubusercontent.com/2477709/95412347-83fa3000-0974-11eb-856c-758a25f63baf.png)

**Comment by jonathan-schmieg** [comment]
this bug shouldn't have been closed - it still exists

**Comment by watermelonpizza** [comment]
Yeah, :( there has been no progress or anything, I guess?
I can't reopen it.

**Comment by OllisGit** [comment]
Hi!

PS. Sorry, for being late to the party, but I made a "Octoprint sabatical" (no coding, no printing) the last months.

After removing the checkbox ```Show printer display on Desktop``` did you close the popup with the X in the top right corner?

Then it should not appear again.

I will try to fix this in one of the next releases. Toggling the checkbox should directly reflected to the visibillity of the popup.

**Comment by OllisGit** [comment]
Hi @watermelonpizza,

new release 1.25.0 is out.
Please test and give feedback.

Thx, in advance
Olli

**Comment by jonathan-schmieg** [comment]
@OllisGit I can confirm that the issue is solved. Thank you very much!
