### ISSUE TITLE
DLP always shows last print progress

### ISSUE THREAD

**Issue by mordhau5** [OllisGit/OctoPrint-DisplayLayerProgress#178]
One thing I've noticed with DLP across several of my printers is that once a print completes, the Browser Tab and Nav Bar always show the last message they sent (which is usually something like "100% HH:MM). Is there any way to have it clear after a couple minutes, or manually even?

**Comment by OllisGit** [comment]
Hi @mordhau5 ,

why is this needed? I don't see a benefit.

PS. Sorry, for being late to the party, but I made a "Octoprint sabatical" (no coding, no printing) the last months.

**Comment by mordhau5** [comment]
@OllisGit When a print is cancelled the header will read the percentage at which the print was stopped until a new one is started or the server restarted. Or when a print is completed, there's no reason for it to read 100% when I come back the next day. Why should the tab keep that information in the tab title? The purpose of having info in the tab title is to allow quick-checks on progress at a glance and if I print has failed, is cancelled or completes, that info isn't needed anymore.

**Comment by OllisGit** [comment]
Hi @mordhau5,

did you already tested the gcode script-feture from Octoprint?
![image](https://user-images.githubusercontent.com/24205767/106337355-4148c480-6291-11eb-8c3e-07fbf1104878.png)
