### ISSUE TITLE
Distance metrics

### ISSUE THREAD

**Issue by StefanCohen** [OllisGit/OctoPrint-DisplayLayerProgress#179]
Hi,

We discussed the possibility to add a print speed graph in the Dashboard in addition to the layer times graph. This is not the same as the feedrate per layer but closer to the actual average print speed per layer as performed on the printer (as affected by accel/decel, etc...). We already have the lastLayerDurationInSeconds metric. In order to calculate the speed, I see the need for some additional metrics from DLP:

lastLayerDistanceInMm
lastLayerDistanceInMmG0
lastLayerDistanceInMmG1

The distance for each command type can be calculated by accumulating each move like: `math.hypot(currX - oldX, currY - oldY)`. The consumer of the events or API can then calculate the speed either for all, printing or non-printing moves within the layer. 

Some assumptions/questions/discussion points:

1. Z moves are usually insignificant so can be omitted in order to increase efficiency. 
1. Most slicers seems to default to absolute positioning for the positioning (unlike for the E-axis). Do we see any gcode files with relative movements in the wild these days? If yes, then support for G90/G91 and the additional coordinate logic must be added.
1. The calculations can be done during pre-processing, so should not affect print performance in any significant way. Correct?
1. Arc moves (G2/G3) produced by a slicer are still rare but might become common soon due to serial comm limitations at higher speeds.

What do you think?

**Comment by OllisGit** [comment]
Hi @StefanCohen !
Sorry, for being late to the party, but I made a "Octoprint sabatical" (no coding, no printing) the last months.

I am not sure if I understand your request correctly...what is the benefit of such graph?

2) yes, I received a lot of gcode in the last years with both movement-modes. The plugin already handle this for z-height calculation
3) yes, sound like it is possible. to do some  some "coord-magic-calculation"
4) start without "arc-commands" maybe a later feature.
