### ISSUE TITLE
what can I do? :Layer indicator not found in file

### ISSUE THREAD

**Issue by thsrp-bob-roger** [OllisGit/OctoPrint-DisplayLayerProgress#183]
Hello, what should I do in Prusa Slicer in order to have the "layer indicator"?

**As soon as printing starts I have this alert displayed in Octoprint:**
"Attention__ Layer indicator not found in file: 'couverture.gcode'
Check layer pattern in DisplayLayerProgress-Settings and reupload the file! "

**I specify that in the plugin settings:**
-the "Show printer display on Desktop" box is checked
-the "Add Layer-Indicators during upload" box is checked

**Comment by OllisGit** [comment]
Hi @thsrp-bob-roger,

please add your sliced gcode file to this issue.
Do you chaged the layer-expressions in the plugin-settings, if yes please also attach the text here.

Btw. did you read the wiki: https://github.com/OllisGit/OctoPrint-DisplayLayerProgress/wiki/How-does-the-plugin-works
