### ISSUE TITLE
100% completed overlaps Layers text

### ISSUE THREAD

**Issue by Jeff-Haas** [OllisGit/OctoPrint-DisplayLayerProgress#184]
![image](https://user-images.githubusercontent.com/27331078/99365877-b1d46d80-286c-11eb-8ba8-2a77f64ce9f8.png)

Picture shows what I'm getting.

Other Octorprint plugins installed that could affect this:
Floating Navbar
Themeify

Browser: Firefox, on Windows 10

**Comment by OllisGit** [comment]
Hi @Jeff-Haas ,

you can adjust the output in the plugin-settings:
![image](https://user-images.githubusercontent.com/24205767/104478861-138e2b00-55c3-11eb-9435-5a6409789221.png)

E.g. shorten the labels or remove it or choose a smaller font.

**Comment by Jeff-Haas** [comment]
Thanks!  I hadn't found that part of the UI yet.
