### ISSUE TITLE
DLP 1.24.0 is trigerring a filament change?

### ISSUE THREAD

**Issue by LordDarkneo** [OllisGit/OctoPrint-DisplayLayerProgress#185]
Hello there,

Since the last update, I think I figoured out an issue with the version 1.24.0. When starting a print, hereunder what's triggered by the plugin:

`2020-11-26 08:42:37,111 - octoprint.events.fire - DEBUG - Firing event: DisplayLayerProgress_feedrateChanged (Payload: {'changeFilamentTimeLeft': '-', 'feedrate': '9000', 'updateReason': 'feedrateChanged', 'totalHeight': '14.6', 'totalLayer': '73', 'estimatedEndTime': '21:37', 'changeFilamentCount': 0, 'estimatedChangedFilamentTime': '-', 'printTimeLeftInSeconds': 46478, 'totalHeightFormatted': '14.6', 'currentHeight': '1.80', 'printTimeLeft': u'12h54m38s', 'lastLayerDuration': '0h:17m:36s', 'averageLayerDurationInSeconds': 864, 'lastLayerDurationInSeconds': 1056, 'changeFilamentTimeLeftInSeconds': 0, 'averageLayerDuration': '0h:14m:24s', 'feedrateG1': '1500', 'feedrateG0': '9000', 'fanspeed': '100%', 'progress': '16', 'currentHeightFormatted': '1.8', 'currentLayer': '8'})
`
thus I have a M600 like trigerred on the printer (and not on octoprint). So i absolutely need to be close to the printer (because the filament is pulled out).

I tried few other "pausing" actions on my octoprint 1.4.2:
- Pausing from octoprint: the print is paused and the nozlle secured. The printer displays 'Paused" ans the filament is not pulled out. When resumong the print from octoprint, everything is starting back
- Pausing trigerred by the filament sensor: I have exaclty the same behavior.

This is why I activated the debug level on Octoprint (attached) and found out that it seems to be trigerred by DLP. 

Could you please tell me where and how to fix this? 

I will try 2 tests; first is printing the gcode from SD (ongoing), and then printing the Gcode with octoprint, but I will deactivate DLP first (to see how it goes).

[octoprint (4).log](https://github.com/OllisGit/OctoPrint-DisplayLayerProgress/files/5604047/octoprint.4.log)

**Comment by OllisGit** [comment]
Hi @LordDarkneo ,

I am not sure why you think DLP is responsible for filament change.

The mentioned log-message only shows that the plugins sends an Event called ```DisplayLayerProgress_feedrateChanged```to the eventbus of OctoPrint. 
Other plugins (e.g. Dashboard) could isten on this event and there own thing.

Please explain a little bit deeper the issue with DLP.
PS. Sorry, for being late to the party, but I made a "Octoprint sabatical" (no coding, no printing) the last months.

**Comment by LordDarkneo** [comment]
Hi everyone,
Sorry for late answer on this topic. I performed many updates/upgrade meanwhile, and the issue has gone... I was thinking about DLP because in the log files, nothing else was triggered for a filament change... 
I'll close this issue
