### ISSUE TITLE
Enhancement request - Send M117 and beginning of layer and every n seconds after that

### ISSUE THREAD

**Issue by Sophist-UK** [OllisGit/OctoPrint-DisplayLayerProgress#192]
I print a mixture of small and large objects. Small objects take only seconds per layer, large objects can take 10s of minutes per layer.

I would really like to see my printer screen updated with an M117 at the beginning of every layer regardless of how long since the last M117 was sent, and then have another M117 sent x seconds later if we haven't started a new layer since.

Is this possible please?

**Comment by OllisGit** [comment]
Hi @Sophist-UK ,

have you tried the [Dashboard-Plugin](https://plugins.octoprint.org/plugins/dashboard/) ? There is a Layer-Duration graph.

**Comment by Sophist-UK** [comment]
@OllisGit Thanks for the pointer - which I will definitely use, however that is not a fix for the message issue identified.

**Comment by Sophist-UK** [comment]
I would still like this issue to be addressed.

**Comment by OllisGit** [comment]
Hi @Sophist-UK,

fyi: I added your idea to my "Idea-Planing-Board".

**Comment by Sophist-UK** [comment]
Thx.

**Comment by Sophist-UK** [comment]
I still would like this implemented. Bumping to stop the bot from closing it.

**Comment by Sophist-UK** [comment]
I still would like this implemented. Bumping to stop the bot from closing it.

**Comment by Sophist-UK** [comment]
I still would like this implemented. Bumping to stop the bot from closing it.

**Comment by Sophist-UK** [comment]
I still would like this implemented. Bumping to stop the bot from closing it.

**Comment by Sophist-UK** [comment]
I still would like this implemented. Bumping to stop the bot from closing it.

**Comment by Sophist-UK** [comment]
I still would like this implemented. Bumping to stop the bot from closing it.

**Comment by Sophist-UK** [comment]
I still would like this implemented. Bumping to stop the bot from closing it.
