### ISSUE TITLE
[Request] Support of M73 progress

### ISSUE THREAD

**Issue by OllisGit** [OllisGit/OctoPrint-DisplayLayerProgress#193]
See https://github.com/OllisGit/OctoPrint-CostEstimation/issues/7

There should be an option to show the M73 progress values provided from the sliced gcode.

Easiest implementation:
- Add new keyword beside ```[progress]```, just add ```[M73progress]```
- Listen for M73 GCode and use this value output-pattern

**Comment by OllisGit** [comment]
Hi @WarrenSchultz,
can you please provide a sample g-code file with included M73 commands?

Thx, in advance
Olli

**Comment by WarrenSchultz** [comment]
Sure, here go go:


[3DBenchy_Repaired_0.2mm_PLA_MK3SMMU2S_1h27m.gcode.zip](https://github.com/OllisGit/OctoPrint-DisplayLayerProgress/files/5832086/3DBenchy_Repaired_0.2mm_PLA_MK3SMMU2S_1h27m.gcode.zip)

**Comment by OllisGit** [comment]
Hi @WarrenSchultz ,

new release 1.25.0 is out.
Please test and give feedback.

Thx, in advance
Olli

**Comment by WarrenSchultz** [comment]
Thanks for looking into this. The filament manager plugin is currently not deploying properly (bugs are logged there already), so I can't test it yet fully. 

The Dashboard plugin is reporting this error with the new version, not sure if that's a bug on this side or that one.
![image](https://user-images.githubusercontent.com/8450968/106374064-8f230280-634d-11eb-9b5d-ca3b295a3729.png)

Actually, looking at this, it appears that this isn't deploying correctly either. It names the plugin Unknown when requesting a restart post-install attempt.

**Comment by OllisGit** [comment]
Hi @WarrenSchultz,

is the DashBoard-Plugin working with lates DLP 1.25.3?

**Comment by WarrenSchultz** [comment]
Looks like it, thanks!

**Comment by hayden-t** [comment]
Hi, I have 1.28 and there seems to be no m73 sent ?? i dont see any options mentioning it either ? I get the stats via m117 though.
