### ISSUE TITLE
Format "Print Time Left" on Printer Display

### ISSUE THREAD

**Issue by QS98** [OllisGit/OctoPrint-DisplayLayerProgress#195]
How can i change the output type of printtime left on the printer display?

I want just the hours and minutes to be shown and not the seconds.

Example:
Print time left 125min -> there should be displayed: 2h 5min
and not 2h 5min 3s !!!

**Comment by OllisGit** [comment]
Currently not possible!

**Comment by OllisGit** [comment]
Hi @QS98,

new release 1.25.0 is out. 
It is now possible to cut the seconds (default).
Please test and give feedback.

Thx, in advance
Olli

**Comment by QS98** [comment]
Very nice!!! Works perfect!
Thank you very much!!!

**Comment by QS98** [comment]
@OllisGit
