### ISSUE TITLE
Layer numbering starting point (0 or 1)

### ISSUE THREAD

**Issue by deejay2** [OllisGit/OctoPrint-DisplayLayerProgress#197]
PrusaSlicer is numbering lines from 1 to N. 
DisplayLayerProgress does it from 0 to N. 

Is there a way to tell DisplayLayerProgress to count from 1 instead of 0? If not, feature request here ;) 

Thank you!

**Comment by OllisGit** [comment]
Hi @deejay2,

already there!!!
Just use the Layer-Offset in the plugin-settings:
![image](https://user-images.githubusercontent.com/24205767/106334803-b2857900-628b-11eb-826f-63527eb97be6.png)
