### ISSUE TITLE
New version  breaks dashboard

### ISSUE THREAD

**Issue by KenLucke** [OllisGit/OctoPrint-DisplayLayerProgress#201]
After installing the latest version, Dashboard no longer recognizes the Display Layer Progress information
 
<img width="828" alt="image" src="https://user-images.githubusercontent.com/57936294/106371383-8106bf00-6318-11eb-9663-39879883bab3.png">

Reverted to 1.24 and everything works again

**Comment by Extra-Fox** [comment]
Same problem here. It showed up in the plugin managers "clean up" tab. I've tried re-installing it twice now and nothing happens.

**Comment by Stephan296** [comment]
You can go back to version 1.24 to use: ```https://github.com/OllisGit/OctoPrint-DisplayLayerProgress/releases/download/1.24.0/master.zip``` in the plugin manager

**Comment by OllisGit** [comment]
Hi,

new bugfix version [1.25.1](https://github.com/OllisGit/OctoPrint-DisplayLayerProgress/releases/tag/1.25.1) is out.
Sorry, forgot to add new file to git repository.

BR
Olli

Duplicated, tracked here: #203

**Comment by KenLucke** [comment]
> new bugfix version [1.25.1](https://github.com/OllisGit/OctoPrint-DisplayLayerProgress/releases/tag/1.25.1) is out.

Will try it when prints are done (soonest one is 84 more hours)
