### ISSUE TITLE
[FR] Mirror Printer Display

### ISSUE THREAD

**Issue by BlackMelt** [OllisGit/OctoPrint-DisplayLayerProgress#211]
Hi there,

first of all, thank you for your efford by keeping this Plugin working.
I was wondering if it's even possible to show the Complete Maschine's Display inside the of the Plugins Screen Overlay.

Would be great if there are is anybody out there who has it may implemented or has a Workaround for this 

Thank you in advance

**Comment by OllisGit** [comment]
Hi @BlackMelt,

it is not possible, because each printer use a different display and firmware. 
So there is no standardized interface/APPI to collect the values.

Simplest solution: Connect a WebCam in front of the Display and show that video-stream in OP ;-)
