### ISSUE TITLE
Conflict with color change pause script

### ISSUE THREAD

**Issue by santanig5** [OllisGit/OctoPrint-DisplayLayerProgress#212]
Greetings,
I've discovered that when using my post processing script I get an error with DLP.
I've attached the log file and gcode file for review.
It appears to me, that DLP has an issue with the replace M117 command.

_post processing script:
;Filament change code below. Specify layer to swap filament. Print will pause and you can change filament, click LCD button to resume print.
{REPLACE "; layer" "M117 Layer"}; show layer number and Z height on LCD
{REPLACE " Z = " " Z="}; make room on LCD for text
;{REPLACE "\nM117 Layer 4, Z=" "\nG1 X10 Y5\nM300 S1000 P1000\nM600\nM117 Layer 4, Z="}; pause at layer, move head, play sound_

[plugin_DisplayLayerProgress_events (1).log](https://github.com/OllisGit/OctoPrint-DisplayLayerProgress/files/6103504/plugin_DisplayLayerProgress_events.1.log)
[3DBenchyDisplayLayerTest.gcode.TXT](https://github.com/OllisGit/OctoPrint-DisplayLayerProgress/files/6103508/3DBenchyDisplayLayerTest.gcode.TXT)

Thank You!

**Comment by OllisGit** [comment]
Hi @santanig5,

please specify the error! What did you expect? 

Where did you put the "post processing script" into your slicer or into OP?
