### ISSUE TITLE
Layer indicator not found in file

### ISSUE THREAD

**Issue by flummy1978** [OllisGit/OctoPrint-DisplayLayerProgress#213]
Hello,

at first sorry for my bad english... its not my native language. I've issues with the DisplayLayerProgress Plugin: 

It doesen't matter how i upload the file, it doesn't matter what ever i change in the code. The error "Layer indicator not found in file" still occurs ;(

I m not sure if i miss something, but i tried different settings inside the regex but nothing works. I'm using Simplify3d. Part of my gcode inside an uploaded file is like:

```
; process Process1
; layer 1, Z = 0.120
T0
; tool H0.120 W0.510
; skirt
...
....
.....
G1 X143.823 Y67.056 E6.6506
G1 X143.587 Y66.820 E6.6585
; layer 2, Z = 0.220
M106 S153
; tool H0.100 W0.300
; inner perimeter
G1 X115.471 Y72.172 F12000
G1 Z0.220 F1002
```
So i have the layer information inside the gcode ?

In the layer tab of DisplayLayerProgress there is now:
1 [; layer ([0-9]+),.*]
1 [;\s+layer\s+([0-9]+),.*]
With setting default, its the same 

The only information that i get inside the layer informations:
Progress: 11% Layer: - of - Height: 2.3 of -mm

Anyone have an idea what it could be ?

Thanks in Advance
Greetings
Andreas

**Comment by OllisGit** [comment]
Hi @flummy1978,
I could not reproduced the issue.

I created a new file and added your mentioned lines to it, upload via drag & drop and after selecting the file it shows maxLayer of 2.

Because in your mentioned expressions there is a missing ```*```, please use the "Reset Settings -Button" (or copy this default-values)
```
1		[;\s*LAYER:\s*([0-9]+).*]		CURA
1		[; layer ([0-9]+),.*]		Simplify3D
1		[;LAYER:([0-9]+).*]		ideaMaker
count	[; BEGIN_LAYER_OBJECT.*]		KISSlicer
count	[;BEFORE_LAYER_CHANGE]		Slic3r
```

The default expression should work with Simplify3d.

If you have still issues, please attach a full file and also the full content of the expression textarea.

**Comment by flummy1978** [comment]
Hi Olli,

thanks for your answer and trying to help me. I hope i dont understand something wrong, but i try to explain: (Deutsch wäre wirklich einfacher **g** ) 

The '*' was missed, cause git cut it in the posting ... however, In my definition there was in both lines one like
`1 [; layer ([0-9]+),.*]
1 [;\s+layer\s+([0-9]+),.*]`

But .... I've tried it once again and also reset and try again with the default expression. 

Ive tested cpl files, and here ist on of them: "EFP_01_M4P.gcode" 
[EFP_01_M4P.zip](https://github.com/OllisGit/OctoPrint-DisplayLayerProgress/files/6265212/EFP_01_M4P.zip)

After that loading, i got this screenshot: 
![screen_octo](https://user-images.githubusercontent.com/49339206/113724022-388dc800-96f2-11eb-8c26-3fe52ccc9b81.jpg)


That was my expression before i changed (now its default) 


![screen_octo2](https://user-images.githubusercontent.com/49339206/113724198-68d56680-96f2-11eb-99f3-5fe50184c049.jpg)


I thought i can fix it by myself, but it seems, i dont get it ;( 

Thanks in Advance for your help

**Comment by OllisGit** [comment]
Hallo @flummy1978,

ich denke ich habe den Fehler gefunden, allerdings solltest du den Fehler auch gesehen haben.

Wenn ich deine Expressions aus dem Screenshot bei mir eintrage und auf Speichern drücke, erscheint diese Fehlermeldung:
```
ERROR in LayerExpression! Line: 3 Message: 'invalid literal for int() with base 10: '''
``` 
Wird diese Meldung bei dir nicht angezeigt? Die wird (sollte) immer angezeigt werden wenn sich die Expressions ändert und Fehler enthalten.

Ursache: die Speichern-Funktion kommt aktuell mit Leerzeilen nicht zurecht. 

- Entferne die Zeilen 3-6
- Speicher die Einstellungen
- Das Model neu hochladen und auswählen

Nun sollten die 326 Layer angezeigt werden.

Werde den Leerzeilen-Fehler in der nächsten Version beheben.

**Comment by OllisGit** [comment]
hmm....schwieriger Fall ;-)

Probier noch mal die Default-Expressions und ändere mal das Encoding der gcode Datei auf ISO-8859-1. Z.B. mit VS-Code oder einem anderen Texteditor.

**Comment by OllisGit** [comment]
Noch ein Punkt: Verwendest du eine GCode-Datei die du von OP heruntergeladen hast.
Wenn ja, entfernen die letzten drei Zeilen und lade die Datei hoch.
```
; BEGIN DISPLAYLAYERPROGRESS SETTINGS
; DisplayLayerProgress_layerIndicatorProcessed = true
; END   DISPLAYLAYERPROGRESS SETTINGS
```

**Comment by OllisGit** [comment]
just for the records: empty "expression-line" are now ignored (since 1.27.0)
