### ISSUE TITLE
[FR] Add new placeholder for the file name

### ISSUE THREAD

**Issue by Majestry** [OllisGit/OctoPrint-DisplayLayerProgress#214]
It will be a nice feature to add new placholder, which will be replaced with the file name when sending to the printer.
For example, something like this
_[current_print_filename]_
Then the output the printer can be like  progress is 
_[current_print_filename] progress is [progress]% L=[current_layer]/[total_layers]_

**Comment by OllisGit** [comment]
Hi @Majestry,
fyi: will be in the next release. 

BUT if you use this parameter in "Print Display", the M117 message could be really long. Be aware of this:
![image](https://user-images.githubusercontent.com/24205767/113512206-cdae8680-9563-11eb-9a5b-9beca52bb652.png)

**Comment by Majestry** [comment]
Cool! Thank you a lot! 
Yes, i know about the long texts. Hoperfully, my printer just shows 64 symbols and simply cut other text. (Ender 3 v2 with Jyers firmware)

**Comment by OllisGit** [comment]
Hi @Majestry 

new release 1.26.0 is out, please test and give feedback.

Thx, in advance
Olli

**Comment by Majestry** [comment]
Yes, it works.
Checked with latin file names
Printer display message in settings: 
_[current_print_filename] Layer [current_layer]/[total_layers]. Heigth [current_height]/[total_height]mm._
Printer display output: 
![photo_2021-04-08_12-48-53](https://user-images.githubusercontent.com/2823715/114014346-cee3fa00-9868-11eb-9f4a-292f981a3ba5.jpg)
