### ISSUE TITLE
"layer indicator not found in file" when sliced in PrusaSlicer (;[layer_z] has been added to the Before Layer Change G-Code)

### ISSUE THREAD

**Issue by sjgcornish** [OllisGit/OctoPrint-DisplayLayerProgress#217]
This prevents the upload of a g-code file to be completed and the progress indicators just keep spinning.  It was working fine before upgrading to the latest release. The [;layer_z] is in the Before layer Change G-code. Note this still happens in Safe Mode

DisplayLayerProgress does work when using the Cura Slicer although I am not sure it plays well with the Cura plugin "Display Progress on LCD" I need to investigate this further and may be a separate issue.

How can I disable this DisplayLayerProgress plugin or downgrade it to an earlier version.

**Comment by OllisGit** [comment]
Hi @sjgcornish,
this issue has nothing to do with this forum-entry, right?

https://community.octoprint.org/t/displaylayerprogressplugin/32028/2
 
Downgrading to an early version is done via Plugin Manager: Uninstall current version and then install older version via providing the release url (e.g. https://github.com/OllisGit/OctoPrint-DisplayLayerProgress/releases/download/1.24.0/master.zip)

BUT which version should work for you and btw. if you execute OP in safe-mode all 3rd party plugins were disabled.

Please describe all steps how I can reproduce the issue (e.g. Slicer-, OP, DLP, Python-Version).
