### ISSUE TITLE
Rest API to get latest Printer Display message

### ISSUE THREAD

**Issue by thebeline** [OllisGit/OctoPrint-DisplayLayerProgress#218]
I haven't dug too much, but I was wondering what one would do to get the latest Printer Display message via the REST API, or if it is even possible.

I set many messages via `M117` commands in my G-CODE files, and would love to be able to get the latest message via your plugin (since it also supports the Printer Display), whether it is a message I sent, or the latest your plugin sent is irrelevant, I would just like which ever was the latest.

Guidance?

**Comment by OllisGit** [comment]
Hi @thebeline,

currently only the parameter-values could be read via REST-API call (see https://github.com/OllisGit/OctoPrint-DisplayLayerProgress#rest---api). Not the message-template and not the latest M117 message.

I can add the latest M117-Message to that parameter list (no big deal), but you need to call regularly the rest-endpoint to receive the lastest message.

An other option is to use the WebSocket-API to get informed if something is changed "OctoDash-Plugin" us this approach.

Please give a feedback about adding the latest 117 message to the rest and/or websocket api!
