### ISSUE TITLE
Way to move printer display box to suit layout

### ISSUE THREAD

**Issue by tuxmob** [OllisGit/OctoPrint-DisplayLayerProgress#219]
Sorry if this is the wrong place to post this and thank you for the very useful plugin.

Is there a way that I have missed to position the printer display box because at the moment its obscuring the print details and files.

Thank you!

**Comment by OllisGit** [comment]
See plugin-settings:
![image](https://user-images.githubusercontent.com/24205767/113505643-777c1c00-9540-11eb-8012-54cb63d02b9d.png)
You need to play around with the class/stack parameters. Tae a look into the orig. description (see link)
