### ISSUE TITLE
Problem with MAXZ

### ISSUE THREAD

**Issue by Neokamikaze** [OllisGit/OctoPrint-DisplayLayerProgress#223]
Hello,

I have a problem with MAXZ value. This don't read in interface but the value is in the gcode file. 
**Example:** 
;MINZ:0.2
;MAXX:122.872
;MAXY:120.044
;MAXZ:25.4
;POSTPROCESSED
;Generated with Cura_SteamEngine 4.8.0
M82 ;absolute extrusion mode

Thanks

![image](https://user-images.githubusercontent.com/10616025/115108548-5f10f600-9f71-11eb-9f7a-aae806c88c5f.png)
![image](https://user-images.githubusercontent.com/10616025/115108581-91225800-9f71-11eb-9add-0aa26ce5c0b7.png)

**Comment by Neokamikaze** [comment]
Hello, 
Fixed using Print Time Genius Plugin
Ciao

**Comment by Doormat1** [comment]
I'm having the same issue. How does print time genius fix this?

**Comment by OllisGit** [comment]
@Doormat1  Good question!
@Neokamikaze, please answer!

@Doormat1, please provide a sample gcode where the maxz was not detected. Btw. the total height is provided by OP itself.
When the value is not detected, please take a look into the op-metafile, located in the uploads-dir of op-installation.
The ```.metadata.json``` should include this section:
![image](https://user-images.githubusercontent.com/24205767/119461644-3209ed00-bd40-11eb-8fa3-bbdc5efbf0a7.png)

**Comment by Doormat1** [comment]
None of my gcodes have anything in the analysis part of the json.

**Comment by Doormat1** [comment]
I guess Display Layer Progress requires Print time genius to work properly, as Ive run M503 on my printer and now Im getting a star next to g code files and Im getting max z height.

**Comment by OllisGit** [comment]
Hi @Doormat1,

PTG is not needed ! 

Did you de-activate ('Never" selected) the analyse feature in OP-Settings? That could be the reason where there is no metadata in the file.

![image](https://user-images.githubusercontent.com/24205767/119568133-72538480-bdad-11eb-84a9-32efc9e8b00a.png)
