### ISSUE TITLE
Not possible to use 24h time format?

### ISSUE THREAD

**Issue by hapklaar** [OllisGit/OctoPrint-DisplayLayerProgress#224]
The plugin only shows am/pm time format for me, I would like to have this in 24h notation.

![image](https://user-images.githubusercontent.com/7703320/115145521-3280db00-a052-11eb-9ad9-04643cccdb25.png)

In configuration I have this set this which should give me 24h format right?:

![image](https://user-images.githubusercontent.com/7703320/115145531-475d6e80-a052-11eb-877c-a97cf822da35.png)

**Comment by OllisGit** [comment]
@hapklaar time format option for the current time will be in the next release.

**Comment by hapklaar** [comment]
I haven't been able to test as I've since moved to Klipper + Fluidd. As soon as I have the chance I will though and report back if there are issues. Will close for now.
