### ISSUE TITLE
Layer indicator not found in file

### ISSUE THREAD

**Issue by renegadecitizen** [OllisGit/OctoPrint-DisplayLayerProgress#225]
im trying to get this to work
but I keep getting this error
Layer indicator not found in file
<img width="1440" alt="Screen Shot 2021-04-18 at 11 44 00 AM" src="https://user-images.githubusercontent.com/6202311/115155143-cbf0c280-a03b-11eb-918f-24ed85688ff4.png">
I have the post processing script in Cura
that adds
M117 INDICATOR-Layer[layer_num]
but when I check the Gcode
and search for m117
Cura did not change [layer_num]
<img width="1440" alt="Screen Shot 2021-04-18 at 11 53 26 AM" src="https://user-images.githubusercontent.com/6202311/115155396-0b6bde80-a03d-11eb-86dd-bfd86ae834f8.png">
I think this is how you get this plugin to work
if you can help me it would be greatly appreciated

**Comment by OllisGit** [comment]
Hi @renegadecitizen,
out of the box cura add  correct layer information into the gcode. And DLP can use the default-expressions to indicate such infos:
```
;LAYER:2
```
So, why do need to add a  post processing cura-script?
