### ISSUE TITLE
[total_height] not accurate for layer heights other than 0.2 mm [CURA]

### ISSUE THREAD

**Issue by Atomique13** [OllisGit/OctoPrint-DisplayLayerProgress#228]
Hello

[total_height] is not accurate for layer heights other than 0.2 mm. It shows 6.62 mm instead of 6.72 mm for 0.32 layer height or 7.08 mm instead of 6.96 mm for 0.08 layer height (I tried on others prints and the same problem). MAXZ in gcode, after DLP post-processed it, shows **;MAXZ:6.72** or **;MAXZ:6.96**, which are good. I added +1 layer offset in Layer settings because CURA adds +1 layer for purge line on the left side, if that helps. I am using DLP 1.26.0 ,CURA 4.9.0, Octoprint 1.6.0 and Creality Ender 3 V2 . Thank you

![image](https://user-images.githubusercontent.com/31422391/116801753-3cf0a980-ab15-11eb-9ffa-1c9ce9936858.png)
GCODE 0.08 Layer Height

![image](https://user-images.githubusercontent.com/31422391/116801961-8641f880-ab17-11eb-8530-321edf7147a2.png)
GCODE 0.2 Layer Heigh

![image](https://user-images.githubusercontent.com/31422391/116801346-cb632c00-ab11-11eb-8631-42d2397a3652.png)
GCODE 0.32 Layer Height

![image](https://user-images.githubusercontent.com/31422391/116801705-e5523e00-ab14-11eb-85ef-bc5411cf1752.png)
Octoprint 0.08 Layer Height

![image](https://user-images.githubusercontent.com/31422391/116801955-7de9bd80-ab17-11eb-9538-acc547eac328.png)
Octoprint 0.2 Layer Height

![image](https://user-images.githubusercontent.com/31422391/116801313-55f75b80-ab11-11eb-99e3-4c7f98426845.png)
Octoprint 0.32 Layer Height

**Comment by OllisGit** [comment]
Hi @Atomique13 ,

DLP reads the total height from Octoprints Metafile. Please take a look
``` <op-installation>/uploads/.metadata.json```
Example:
![image](https://user-images.githubusercontent.com/24205767/117634978-bc1e5700-b17f-11eb-86db-98dc8f5b907b.png)

Maybe there is something wrong in OP.

**Comment by Atomique13** [comment]
Hello again,

![image](https://user-images.githubusercontent.com/31422391/118756386-7b0afe80-b873-11eb-9e8b-ea136780159a.png)
.metadata.json 0.08 Layer Height

![image](https://user-images.githubusercontent.com/31422391/118756308-4bf48d00-b873-11eb-897d-c9bbba020948.png)
.metadata.json 0.2 Layer Height

![image](https://user-images.githubusercontent.com/31422391/118756156-ffa94d00-b872-11eb-9f13-bcc74123d38e.png)
.metadata.json 0.32 Layer Height

**Comment by Sekisback** [comment]
still open DPL calculate one Layer above MAXZ
