### ISSUE TITLE
GCode Viewer Layer Information

### ISSUE THREAD

**Issue by JaniDJ** [OllisGit/OctoPrint-DisplayLayerProgress#235]
Hello there, 
would it be possible to use the existing layer information from octoprint? Like many others, I have already uploaded a lot of gcode files to octoprint, and I honestly don't want to upload them again. I know octoprint shows the current layer in the gcode viewer, so shouldn't there be a way to use that information instead of modifying the gcode? 

Thank you so much for the great plugin! It's really a pleasure to use it, especially now that I can finally use the LCD of my Ender 3 v2 for such information.

Cheers Jani

**Comment by CmdrCody51** [comment]
Specifically for j-n7 (and others) I have a script to reload all your files for you.
[Reload.sh.zip](https://github.com/OllisGit/OctoPrint-DisplayLayerProgress/files/8240142/Reload.sh.zip)
This is kind of dangerous as you RPi will be quite busy reprocessing all your files 8-)
Read it before using it - I run it from my .octoprint directory.
