### ISSUE TITLE
Wrong format token for minutes in "Show current time"

### ISSUE THREAD

**Issue by fnsign** [OllisGit/OctoPrint-DisplayLayerProgress#239]
The default entry in "Show current time" is given as "HH:MM". This leads to a wrong display of the current time as the token MM shows the current month as decimal. Meaning the minutes seem to be stuck at "10" (October). The correct format token is "mm" (lower case).
The default value should be corrected to "HH:mm" instead to display minutes correctly and avoid irritations for the users.

See also https://momentjs.com/docs/#/displaying/format/

**Comment by OllisGit** [comment]
Upps!

@fnsign thanks for the bug-report. It is now fixed in latest version 1.27.1.
