### ISSUE TITLE
Octoprint counts all print layers twice (solved)

### ISSUE THREAD

**Issue by sebbl2** [OllisGit/OctoPrint-DisplayLayerProgress#240]
It seems that I am the only person with this issue.
Since the update to 1.27.1, DisplayLayerProgress shows exactly twice the number of actual layers. In Prusaslicer the layer count is still correct.
The whole thing in connection with Prusa MK3s+

Tried: Plugin uninstalled, FW MK3s reloaded

It could be related  to OP 1.7, because when downgrading DLP the problem still exists.

**Comment by sebbl2** [comment]
We should leave this open/visible to others

**Comment by sebbl2** [comment]
Nope, I didn't customise anything in there

**Comment by kcdr** [comment]
Same for me.
At least my PrusaSlicer (v2.3.3) emits both (;LAYER_CHANGE and ;BEFORE_LAYER_CHANGE)

**Comment by OllisGit** [comment]
Discussion from PR  https://github.com/OllisGit/OctoPrint-DisplayLayerProgress/pull/238#issuecomment-964645434
> 1. revert this pull and back out, and update docs to tell people to add BEFORE_LAYER_CHANGE to their printer profile
> 2. if plugin matches more than one filter use only first match (i am unclear if it does this already?)

Hi @scyto,

I think option 2 is the correct solution.

Currently the plugin scans each gcode-line agains each layer-expression. That doesn't make sense and reproduce the mentioned error. 

I will change it to this behaviour: scan each gcode-line agains each layer-expression, after one expression matched it will be taken for the rest of following gcode-lines.

**Comment by OllisGit** [comment]
Hi,

now implemented in Version 1.27.2.

Please test and give me feedback

Thx, in advance
Olli
