### ISSUE TITLE
After ussing SuperSlicer i can`t see the layers anymore.

### ISSUE THREAD

**Issue by Willy3D** [OllisGit/OctoPrint-DisplayLayerProgress#243]
After switching to SuperSlicer from Simplify 3D i can`t see the layer, i get a message "Layer indicator not found in file: '_SS_Test-prints/SS_Evo_xyzCalibration_cube.gcode'
Check layer pattern in DisplayLayerProgress-Settings and reupload the file!"
But what must i fill in to see the layers again.

Layer output from SuperSlicer:
;LAYER_CHANGE
;Z:2.1

**Comment by OllisGit** [comment]
This line now added since version V1.27.0
