### ISSUE TITLE
Timezone setting for [estimated_end_time]

### ISSUE THREAD

**Issue by Zuckme** [OllisGit/OctoPrint-DisplayLayerProgress#245]
Your plugin is awesome, thanks!

I have Octoprint installed on a FreeBSD Laptop with UTC system time on it.
Guess what, the [estimated_end_time] are UTC and not in my current time zone.

Could you please add a timezone adjustment?

Not super important, but it should be easy to implement....

**Comment by OllisGit** [comment]
...and it is not possible for you to change the timezone on the Laptop?

**Comment by Zuckme** [comment]
Yeah... I am imbarassed.... fixed..

https://linuxhint.com/change-freebsd-timezone-2/

I activated also a NTP sync...

There is always something to learn in FreeBSD.

Solved.
