### ISSUE TITLE
Feature request: send to nav bar but not to M117 status bar

### ISSUE THREAD

**Issue by galfridus** [OllisGit/OctoPrint-DisplayLayerProgress#250]
I have Cura printing M117 "time left" messages which tend to be more accurate than even the PrintGenius plugin. Unfortunately, the updates from this plugin overwrite those so I never see them. Is there a way to have this plugin leave the M117 status alone and just show in the top status bar of Octoprint?

**Comment by OllisGit** [comment]
Hi @galfridus,

maybe you didn't saw the plugin-settings, but there you can disable the "printer display". Then DLP will not send  additional M117 messages to the printer. 

![image](https://user-images.githubusercontent.com/24205767/150869539-f414c3c2-32be-407a-be41-09b47e65bac9.png)
