### ISSUE TITLE
navbar timezone correction

### ISSUE THREAD

**Issue by martan223** [OllisGit/OctoPrint-DisplayLayerProgress#258]
Navbar title shows print finish time wrong (instead showing right finish time, it shows -1 hour, ie, instead of 10:37 it shows 9:37). I suspect that it is due to my timezone (Prague +1). 
p.s. system time is correct.

**Comment by fellnerse** [comment]
I have the same issue, if I add `%Z` to the output I can see that it uses BST aka british timezone, wich is not correct for me. Would be cool if it was possible to set this.

Otherwise I love the plugin!
