### ISSUE TITLE
Cant use this plugin with Octolapse custom trigger?

### ISSUE THREAD

**Issue by pto199** [OllisGit/OctoPrint-DisplayLayerProgress#259]
I have a "search and replace" script running in Cura.  It is:

Search: (;LAYER:).{1,}
Repalce: g4 P1

I need this for my octolapse instance to get properp trigger timing.  The problem is once I replace layer text, this plugin has nothing to see and doesnt work.  What can I do here?  If I goto gcode viewer in octoprint, it still seems to know what layer im on, but this plugin does not.

**Comment by CmdrCody51** [comment]
Don't replace it. Append a new line after the "LAYER:"
Add the "G4 P1" after it.
That way both are happy.
