### ISSUE TITLE
Unable to use plugin at all.  Was working flawlessly

### ISSUE THREAD

**Issue by Gozania** [OllisGit/OctoPrint-DisplayLayerProgress#262]
I run octodash.  There was a github issue with them today that forced a downgrade.  Upon this happening something went awry with my display layer plugin.  After getting octodash back up and running, I noticed I wasnt getting layer info.  I look in the plugin manager and notice its disabled.  Re-enable and nothing.  So I uninstall & cleanup data.  Re-install and now met with a lightning bolt icon stating it cant run be run.  I have tried several times to uninstall and reinstall.  I'm at a loss now and really want this plugin back as I found it massively helpful.   Screenshot attached
![Screenshot 2022-05-09 202925](https://user-images.githubusercontent.com/83924000/167537260-32705bb2-4569-4bb1-89e2-3bce67bfe7e1.jpg)

***UPDATE***
All seems well now.  I think it was a github issue that was forcing me to download previous versions.  Decided to try to unistall and re-install and installed v1.25.4 which is the latest.

**Comment by wademaxfield** [comment]
I've hit the same issue.  I had this plugin running on a Pi 3B+ for the last week using OctoPi 0.18.0 (first printer) I have just set up a new Pi 4 with a clean install of OctoPi 0.18.0 and can not get DisplayLayerProgress to install and run - I have disabled all 3rd party plugins while attempting to diagnose this, but they do not seem to be part of the issue.
