### ISSUE TITLE
Czech language not shown in settings-page

### ISSUE THREAD

**Issue by OllisGit** [OllisGit/OctoPrint-DisplayLayerProgress#27]
Reported by @JanSykor

**Comment by JanSykor** [comment]
Hello @OllisGit 
I translated only Display Z plugin - unfortunatelly this not have any setting page, but translation for Octoprint working also in setting page - if this help
[cs_1_3_7.zip](https://github.com/OllisGit/OctoPrint-DisplayLayerProgress/files/1936053/cs_1_3_7.zip)
What about German language in your plugin?
Thanks
Jan

**Comment by JanSykor** [comment]
Perfect job!!!
Its working
Thank you very much
Where was the problem?
Jan

**Comment by OllisGit** [comment]
to be honest...I have no clue....maybe some bit-jittering

**Comment by JanSykor** [comment]
It does not matter.
Result is important.
:-)
