### ISSUE TITLE
Layer counter shows only - / -

### ISSUE THREAD

**Issue by beejayf** [OllisGit/OctoPrint-DisplayLayerProgress#29]
Layer current and layer total does not show on CR-10 Marlin 1.1.8 for Slic3r gcode files

**Comment by OllisGit** [comment]
Did you already read the information of the start page?

> * The layer information output only works with "Cura"/"Simplify3D" generated G-Code, because these Slicer insert the layer information directly as comments in the file. If you want to use "slic3r", see Enhancement #8

**Comment by beejayf** [comment]
I didn’t – thanks for the hint!

Gesendet von meinem Windows 10 Phone

Von: OllisGit
Gesendet: Montag, 23. April 2018 22:47
An: OllisGit/OctoPrint-DisplayLayerProgress
Cc: beejayf; Author
Betreff: Re: [OllisGit/OctoPrint-DisplayLayerProgress] Layer counter showsonly - / - (#29)

Did you already read the information of the start page?
• The layer information output only works with "Cura"/"Simplify3D" generated G-Code, because these Slicer insert the layer information directly as comments in the file. If you want to use "slic3r", see Enhancement #8

**Comment by OllisGit** [comment]
If you have further issues, please create a new one.
This issue is now closed.
BR
Olli
