### ISSUE TITLE
Conflict w/ Multi Colors

### ISSUE THREAD

**Issue by upD8R** [OllisGit/OctoPrint-DisplayLayerProgress#40]
The plugin conflicts with default settings of the Multi Color Octoprint plugin. This plugin is also looking for the Layer comment field and fails after your plugin has processed the gCode file. I wonder why you replace the comment instead of adding the M117 command?

Anyway, changing the regular expression to "M117 INDICATOR-Layer{layer}" in Multi Colors did the job for me.

Thanks for your work, highly appreciated!

**Comment by OllisGit** [comment]
Thx, for your feedback.
Because I want to be a "good citizen", so I don't want to "crash" other plugins, I will change the behaviour in the next release.

BR
Olli

**Comment by upD8R** [comment]
Hi Olli,

maybe adding the RegExp above to your documentation is sufficient? It works but there is a dependency. I think a documentation change could be sufficient here.

Your choice 😜

Cheers, Mario

**Comment by OllisGit** [comment]
The new Release 1.6.0 is out. 
The orig. comments are not droped anymore, also now you can define your own layer-comments-expressions.  See Plugin-Settings!

Please test the new enhancement.

Thx, in advance
Olli
