### ISSUE TITLE
height offset

### ISSUE THREAD

**Issue by TomW1605** [OllisGit/OctoPrint-DisplayLayerProgress#42]
every one of my models is consistently shown as .10mm taller than is is

**Comment by TomW1605** [comment]
![2018_05_08 07_12_55](https://user-images.githubusercontent.com/17092573/39729629-83ac9c58-528f-11e8-928a-5e2f335b64f5.png)
![2018_05_08 07_13_01](https://user-images.githubusercontent.com/17092573/39729632-84cae180-528f-11e8-9647-b2f179b5274f.png)
[small spool outside.txt](https://github.com/OllisGit/OctoPrint-DisplayLayerProgress/files/1981764/small.spool.outside.txt) just change the extention back to .gcode it wouldent let me upload with it

**Comment by OllisGit** [comment]
I checked your provided gcode:

`Line 18912: G1 Z16.700 F9000.000`

This is the last Z-Movement in the file, so it looks correct for me.

**Comment by TomW1605** [comment]
sorry the second screenshot there is was of the wrong thing. the gcode viewer in octoprint shows the height for that print as 16.60mm

**Comment by OllisGit** [comment]
okay, the g-code viewer does a lot of "magic-calculation". I looked into the javascript code, but I couldn't understand everthing. So for me "magic" is best word for that.

I use the real values in the g-code!

**Comment by TomW1605** [comment]
ok i have worked out the difrence. you are displaying the height of the nozel however they are displaying the height of the moddle itself. because i print with a .4mm first layer then ofset evrything but -.3mm i get the extra .1mm added to the nozel height. it is worth noting that evry online gcode viewer i can find gives the same height as the octoprint one (it is posable they are all using the same code though).

**Comment by OllisGit** [comment]
thx, for the explanation. I didn't know that.
I will put this information into the documentation.

BR
Olli
