### ISSUE TITLE
option to disable height in sidebar

### ISSUE THREAD

**Issue by TomW1605** [OllisGit/OctoPrint-DisplayLayerProgress#44]
as always i think that the more you can customise the behaviour of a program the more useful it will be to more people.

**Comment by OllisGit** [comment]
....but more effort on developer side ;-)

Currently I am optimizing the Settings-Page. In future I will use tabs, so there is more space for each topic (like visibility, layer-expressions, etc.)

**Comment by OllisGit** [comment]
The new release 1.6.0 is out. 
I added the functionality to show/hide height and layer in statebar.

Please test the new enhancement.

Thx, in advance
Olli
