### ISSUE TITLE
too many log events

### ISSUE THREAD

**Issue by hakan42** [OllisGit/OctoPrint-DisplayLayerProgress#52]
While watching the octoprint.log, the DisplayLayerPlugin completely swamps any other output as it adds a couple of log entries every second.

Maybe that could be reduced to "debug"?

Specifically, it's the "NavBar" log on line 369.

**Comment by OllisGit** [comment]
It's fixed in the new Version 1.7.1.
Please test the enhancement.
Thx, in advance
Olli

**Comment by hakan42** [comment]
Works fine for me now, thank you 👍
