### ISSUE TITLE
Unit conversion

### ISSUE THREAD

**Issue by tonejaco** [OllisGit/OctoPrint-DisplayLayerProgress#53]
Since Cura (and others?) have you input feed rate info in mm/s it would be nice to have the progress display in the same units. Perhaps there are some who might like to see it in other units. Could you add a unit multiplier which would allow any units desired to be displayed? That might also require the ability to add the new unit indicator (i.e. “mm/s”)

**Comment by tonejaco** [comment]
Oh also, is there a way to display only one decimal place?

**Comment by OllisGit** [comment]
hmmm..sounds like a good idea, but from implementation side I need something like a formular- and formatter-pattern parser. 
Maybe I am thinking into the wrong direction. Please explain a little bit more about the need of "any units".
From my point of view only two units are needed.
- mm/minute -> G1 F1500; 1500mm/minute
- mm/s -> 1500/60 == 25mm/second

**Comment by OllisGit** [comment]
@tonejaco 
I released a new Version (1.10.0). Now it is possible to change the feedrate output.
Please test and give a feedback.

Thx, in advance
Olli
