### ISSUE TITLE
Extra spaces?

### ISSUE THREAD

**Issue by tonejaco** [OllisGit/OctoPrint-DisplayLayerProgress#54]
I’ve tried adding extra spaces to the display layer progress format in order to space the different info out a little. I’m guessing it doesn’t support displaying those extra spaces.

**Comment by ukwebb** [comment]
as its displaying as html - try using    &nbsp;   rather than the space character

**Comment by tonejaco** [comment]
Could you spell that in a way that will show up???? 😉
