### ISSUE TITLE
Text Color in Nav Bar

### ISSUE THREAD

**Issue by TechnoSwiss** [OllisGit/OctoPrint-DisplayLayerProgress#55]
The gray colored text in the Nav Bar can be very hard to read on some color schemes. Would it be possible to make the text color a configurable option, or have text color use the Nav Bar text color similar to the M117NavBar (https://github.com/jneilliii/OctoPrint-M117NavBar) plugin? Thanks.

**Comment by OllisGit** [comment]
You can add html-syntax into your "Navigationbar" output-pattern.
Like this:
`<font color="red">Progress: [progress]% Layer: [current_layer] ....</font>`

Hope that helps
Olli

**Comment by TechnoSwiss** [comment]
Perfect! Thank you.
