### ISSUE TITLE
layer value is not shown on cr-10 display

### ISSUE THREAD

**Issue by TheSpirit** [OllisGit/OctoPrint-DisplayLayerProgress#6]
in installed the plugin.
in the navbar i can see the values, but on the display of my cr-10, nothing is shown

**Comment by OllisGit** [comment]
For solving the bug I need more information:

- Which Version of the Plugin do you use? The inital Version 1.0.0 had a bug with M117 message with dots
- Do you use SD- or Local-Storage? I thing the G-Code PreProcessing is only working on local storage. I didn't checked this behaviour with SD-Card storage yet.
- Please download the G-Code from OctoPrint via download button and check that all lines with e.g.  `;LAYER:12` are replaced with `M117 INDICATOR-Layer12`

**Comment by phisher1** [comment]
Using 1.0.2 downloaded via plugin manager.
Not seeing any replacements in downloaded gcode.
Using Local storage, sliced using S3D and uploaded to Octoprint 1.3.7
Seeing Percentage on LCD screen, but not layer information.
Seeing Percentage on Octoprint top bar, but not layer information.
CR-10s running THD Unified firmware based on marlin 1.1.8

**Comment by phisher1** [comment]
Ahh.. Well that would make much more sense. Bummer.. would have liked to use your plugin.  Well, thanks for reply. Cheers!

**Comment by OllisGit** [comment]
The new release 1.1.1 is out. 

**Please could somebody give me a feedback if it works with a CR-10**

Thx, in advance
Olli

**Comment by OllisGit** [comment]
@AbuMaia  hmm...research...this sentence is on the startpage ;-)

> The layer information output only works with “Cura”/”Simplify3D” generated G-Code, because these Slicer insert the layer information directly as comments in the file. If you want to use “slic3r”, see Enhancement #8

**Comment by OllisGit** [comment]
assumtion: plugin works for CR-10 and with "layer-commented" g-code ..if not, please so kind and create a new issue!

Thx,
Olli

**Comment by AbuMaia** [comment]
Ollis: not when installing the plugin through OctoPrint's plugin manager.

**Comment by OllisGit** [comment]
@AbuMaia please so kind and create a new issue which describe the problem, so that it is hopefully reproducible
Thx, in advance
Olli
