### ISSUE TITLE
Updating of czech language

### ISSUE THREAD

**Issue by JanSykor** [OllisGit/OctoPrint-DisplayLayerProgress#63]
Hello @OllisGit
I saw you have made many changes from last time. Could you please update a files for translating?
Thank you
Jan

**Comment by OllisGit** [comment]
Sorry, for the delay and also sorry to say, but supporting multiple languages takes a lot of effort.

This was my first plugin and I tried several function like Muli-Language-Support, but now I will skip this feature.

Bye
Olli
