### ISSUE TITLE
only one digit for layer count

### ISSUE THREAD

**Issue by bookledge** [OllisGit/OctoPrint-DisplayLayerProgress#65]
after this update, layer display is abnormal..
only one digit show on display.

I looked the gcode.
> Previous version
`;LAYER:19
M117 INDICATOR-Layer19`

> This version
`;LAYER:29
M117 INDICATOR-Layer9`

total layer count is also one digit. 
How can i fix this issue?

**Comment by OllisGit** [comment]
ahh...I though I fixed a problem, but a raise a new one, sorry!
For a quick fix go to the settings page, select  layer and
replace: `;.*LAYER:.*([0-9]+).*`
with: `;LAYER:([0-9]+).*`

**Comment by OllisGit** [comment]
no feedback, closed!
