### ISSUE TITLE
Display Estimated Time Left

### ISSUE THREAD

**Issue by TechnoSwiss** [OllisGit/OctoPrint-DisplayLayerProgress#67]
Would be nice to have Print Time Left displayed (as show in OctoPrint web page), well added in as one of the place holders. If I understand the data the plugin has access to correctly, when you do a _printer.get_current_data() the data is available as currentData["progress"]["printTimeLeft"]. The value could be "None" since OctoPrint waits a couple of layers to calculate Print Time Left, in which case it could either display "None" or maybe currentData["job"]["estimatedPrintTime"] with an * or something to denote it's the estimated time.

Thanks

**Comment by OllisGit** [comment]
I like the idea, so I implemented it in a feature branch.
![image](https://user-images.githubusercontent.com/24205767/50993981-448e7d80-151b-11e9-9efe-7b8a155cdee9.png)
You can test the version by downloading via this URL: 
https://github.com/OllisGit/OctoPrint-DisplayLayerProgress/archive/feature/%2367_printtimeleft.zip

After install, just add [printtime_left] in the Printer-Pattern.
If you like it then I will merge this feature into a next major-release.



BR
Olli

**Comment by TechnoSwiss** [comment]
Thanks @OllisGit that works great.

**Comment by OllisGit** [comment]
Feature is now in Version 1.9.0
