### ISSUE TITLE
Feedrate 

### ISSUE THREAD

**Issue by Lolbster** [OllisGit/OctoPrint-DisplayLayerProgress#68]
First: Thank You for this very nice PlugIn.

This is not realy an issue but,
Is it Possible to show feedrates in mm/s, this also give more Place on Printer Display.

**Comment by OllisGit** [comment]
@tonejaco
I released a new Version (1.10.0). Now it is possible to change the feedrate output.
Please test and give a feedback.

Thx, in advance
Olli

**Comment by Lolbster** [comment]
a thats great :-)
works lika a charm!

Thank you SIR

**Comment by OllisGit** [comment]
@Lolbster Your welcome!
