### ISSUE TITLE
Analyse layers without reuploading files 

### ISSUE THREAD

**Issue by h4nc** [OllisGit/OctoPrint-DisplayLayerProgress#72]
Coming from here:
https://community.octoprint.org/t/eta-etl-and-displayed-at-printer-lcd/8736

Would be nice if we don’t need to reupload files so that the layers can be analyzed.

Thanks!

**Comment by OllisGit** [comment]
Hi @h4nc ,
behaviour is changed in the newest version 1.16.0.

Please test and give feedback!

**Comment by h4nc** [comment]
Will do, but at the moment it tells me that 1.15 is the current version.

**Comment by h4nc** [comment]
I'm afraid I can't test this anymore. None of my files is older 4 months. I guess restoring a backup did this. So it looks like I can't confirm that it works. Sry.

**Comment by OllisGit** [comment]
It's not possible to do. The only option could be start manually the layer-analyse. This must be handled in #101
