### ISSUE TITLE
Feature: Last layer time

### ISSUE THREAD

**Issue by agibson2** [OllisGit/OctoPrint-DisplayLayerProgress#74]
I find myself printing things where I would like to estimate how long until my next pause to change the filament color.  I count how many layers until the next color change (@pause).  I put in using a post-processing plugin for Cura so I know many layers until I get there.  I then time a single layer just to get a estimate of how long it might be.  For objects that the layers are pretty consistent, this works well for me to give me some kind of idea.

Any chance for a feature to show the time that the last completed layer took.  Optionally the average of the last 5 layers something like that would be useful too but just having the last layer time would be helpful.

**Comment by OllisGit** [comment]
@agibson2  It will be included in the next version.

**Comment by OllisGit** [comment]
@agibson2 
Done. Version 1.11.0 is out.

Please test and give a feedback.
Thx, in advance
Olli

**Comment by agibson2** [comment]
Thanks.  I missed your previous message announcement.  Thanks for this!  As soon as my current print is done (an hour or so), I will test it out.

**Comment by agibson2** [comment]
It works perfectly.  Thanks.  I used the line below to display minutes and seconds and average.

`LayerTiming:<span sytle='display: inline-block;width:24px;'>[last_layer_duration]</span> , avg <span style='display: inline-block;width:24px;'>[average_layer_duration]</span>`
