### ISSUE TITLE
add support for getting total layer number from last layer change comment

### ISSUE THREAD

**Issue by TomW1605** [OllisGit/OctoPrint-DisplayLayerProgress#8]
this would make it very easy for people to use your plugin with slic3r as well. slic3r allows for custom gcode to be added at each layer change and has a [layer_num] placeholder that lets you duplicate the `;LAYER:0` format from cura. however, slic3r has nothing that gives the total layers. it is possible with post processing but if you could use the last layer change comment then this would not be necessary.

**Comment by OllisGit** [comment]
just to make sure that I understand your enhancment:
- instead of using the `;LAYER_COUNT:` the plugin should use the last `;LAYER:` comment
- slic3r could provide the Cura-Layer format (`;LAYER:`), right!?!

I think this is a realy good enhancement and it should be easy to implement.
I will start implementing this ;-)

**Comment by TomW1605** [comment]
yes it can. under printer settings there are custom gcode options
![2018_04_12 08_27_12](https://user-images.githubusercontent.com/17092573/38650007-1c0fa648-3e2c-11e8-9850-fe6c225bf3cb.png)

**Comment by OllisGit** [comment]
The new Release 1.1.0 is out. Please test the new enhancement.
Thx, in advance
Olli

**Comment by TomW1605** [comment]
it works for me

**Comment by OllisGit** [comment]
Great!

**Comment by reloxx13** [comment]
for lazy guys cuz in the comment its an image

`;LAYER:[layer_num]`

would be nice to have it as default, just trying out slic3r and now the print is without layer count :S

**Comment by vitt82** [comment]
> for the lazy copy&paste guys cuz in the comment above its an image
> 
> `;LAYER:[layer_num]`
> 
> would be nice to have it as default, just trying out slic3r and now the print is without layer count :S

🥇

**Comment by Doprintityourself** [comment]
Hi It is not working for me here
Prusa Slicer 2.2 and 2.3Beta3
I have 
;LAYER:[layer_num]
in bevore layer change gcode
![grafik](https://user-images.githubusercontent.com/70262325/102505417-3db30280-4082-11eb-9927-9ce82fe7a504.png)
but still getting no layer indicator as a warning 
![grafik](https://user-images.githubusercontent.com/70262325/102505668-8f5b8d00-4082-11eb-8317-d45250d9978f.png)
the gcode file contains the wanted line
![grafik](https://user-images.githubusercontent.com/70262325/102505751-a8fcd480-4082-11eb-96c9-9d979dde04c3.png)

but I only see
![grafik](https://user-images.githubusercontent.com/70262325/102505829-c03bc200-4082-11eb-966a-c5bb17be7854.png)
and in top status line layer of is missing
![grafik](https://user-images.githubusercontent.com/70262325/102505885-d3e72880-4082-11eb-9a28-cb80a5109a40.png)

I have uploaded the file new but not working

Interestingly the file should be changed during the upload!?
but it seems totaly the same after download the upload and comparison of the two files
Should the uploaded file be modified?
thanks in advance

**Comment by Doprintityourself** [comment]
Very strange, reset all settings, rebooted and uploaded again, now it seems to work partially
Layer is progressing but total height is still not displayed 
![grafik](https://user-images.githubusercontent.com/70262325/102510453-ef086700-4087-11eb-8013-a5696c2cbe8e.png)

**Comment by Doprintityourself** [comment]
what the hack is going on after finishing it displays higher than total
![grafik](https://user-images.githubusercontent.com/70262325/102511192-c765ce80-4088-11eb-9cd8-6d4793d09914.png)

I will now totally uninstall clean data and do a fresh install

**Comment by Doprintityourself** [comment]
closed seems to work again after wiping data and install an reinstall plugin

**Comment by Doprintityourself** [comment]
Not consistant 
I have installed it on my seccon server fresh, never had this plugin installed before
I have to say that it is a multiple instance install!
Outcome:
first printer 
not working properly 
![grafik](https://user-images.githubusercontent.com/70262325/102521969-e4ed6500-4095-11eb-94fb-450b14317da0.png)
seccond printer on xxx.xxx.xxx:5001
as it should be
![grafik](https://user-images.githubusercontent.com/70262325/102522078-0c443200-4096-11eb-9025-d9ee945febd6.png)

any idea could the plugin fail becaus of mutliple instances?

**Comment by sandboxgangster** [comment]
> ;LAYER:[layer_num]

Simple Thing your must add a SPACE after ; (; LAYER:[layer_num])
