### ISSUE TITLE
add option for putting in sidebar instead

### ISSUE THREAD

**Issue by TomW1605** [OllisGit/OctoPrint-DisplayLayerProgress#9]
this would be quite useful particularly to people who already use plugins that add to the nav bar. it also makes more sense for the remaining layers to be with the progress bar, data printed counter and time remaining estimate as these are all print progress related.

**Comment by TomW1605** [comment]
![2018_04_12 20_30_31](https://user-images.githubusercontent.com/17092573/38677314-7e7dbdec-3e90-11e8-81eb-67d7a0556780.png)
this is the problem with having it in the navbar

**Comment by TomW1605** [comment]
unless it is easy to make the position in the sidebar customisable, i think the best place would be just above the progress bar

**Comment by OllisGit** [comment]
The new Release 1.2.0 is out. Please test the enhancement.
Thx, in advance
Olli
