### ISSUE TITLE
When used with OctoPrint-UltimakerFormatPackage, layers are not calculated

### ISSUE THREAD

**Issue by RomRider** [OllisGit/OctoPrint-DisplayLayerProgress#98]
When I send the job to octoprint using Cura with UltimakerFormatPackage installed and the Octoprint intergration in Cura, Cura sends the file in UFP which includes a thumbnail of the object. The gcode is then extracted by UltimakerFormatPackage.
In this case, DisplayLayerProgress doesn't parse/modify the gcode and thus can't display layer progress.

Is that something which could be implemented?

**Comment by redpizza69** [comment]
That's what the problem is! I've been spending hours trying to work out why DisplayLayerProgress isn't working!

+1 for working with the UltimakerFormatPackage from Cura.

**Comment by OllisGit** [comment]
Hi @RomRider , @redpizza69 
this issue is solved in the newest version 1.16.0.

Please test and give feedback!

**Comment by OllisGit** [comment]
Hi @RomRider , @redpizza69
the new version 1.17.0 is also able to handle ufp-format.

Please test and give feedback!

Thx, in advance
Olli

**Comment by OllisGit** [comment]
New version, new luck!
